# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_RequestSetPreset.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumPresetIcon_pb2 as wsdkCommands_dot_WSDK__EnumPresetIcon__pb2
from wsdkCommands import WSDK_EnumFlatMode_pb2 as wsdkCommands_dot_WSDK__EnumFlatMode__pb2
from wsdkCommands import WSDK_EnumPresetTitle_pb2 as wsdkCommands_dot_WSDK__EnumPresetTitle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_RequestSetPreset.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1bWSDK_RequestSetPreset.proto\x12\rwsdk_commands\x1a&wsdkCommands/WSDK_EnumPresetIcon.proto\x1a$wsdkCommands/WSDK_EnumFlatMode.proto\x1a\'wsdkCommands/WSDK_EnumPresetTitle.proto\"3\n\x1eWSDK_RequestSetPresetEditStart\x12\x11\n\tpreset_id\x18\x01 \x01(\r\"!\n\x1fWSDK_RequestSetPresetEditCancel\" \n\x1eWSDK_RequestSetPresetEditStore\"6\n!WSDK_RequestSetPresetFactoryReset\x12\x11\n\tpreset_id\x18\x01 \x01(\r\"0\n\x1bWSDK_RequestSetPresetRemove\x12\x11\n\tpreset_id\x18\x01 \x01(\r\"\xde\x01\n\x1bWSDK_RequestSetPresetCreate\x12\x10\n\x08group_id\x18\x01 \x01(\r\x12.\n\x04mode\x18\x02 \x01(\x0e\x32 .wsdk_commands.WSDK_EnumFlatMode\x12\x30\n\x04icon\x18\x03 \x01(\x0e\x32\".wsdk_commands.WSDK_EnumPresetIcon\x12\x35\n\x08title_id\x18\x04 \x01(\x0e\x32#.wsdk_commands.WSDK_EnumPresetTitle\x12\x14\n\x0ctitle_number\x18\x05 \x01(\x05\"E\n\x1aWSDK_RequestSetPresetOrder\x12\x11\n\tpreset_id\x18\x01 \x01(\r\x12\x14\n\x0cpreset_order\x18\x02 \x01(\r'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumPresetIcon__pb2.DESCRIPTOR,wsdkCommands_dot_WSDK__EnumFlatMode__pb2.DESCRIPTOR,wsdkCommands_dot_WSDK__EnumPresetTitle__pb2.DESCRIPTOR,])




_WSDK_REQUESTSETPRESETEDITSTART = _descriptor.Descriptor(
  name='WSDK_RequestSetPresetEditStart',
  full_name='wsdk_commands.WSDK_RequestSetPresetEditStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preset_id', full_name='wsdk_commands.WSDK_RequestSetPresetEditStart.preset_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=216,
)


_WSDK_REQUESTSETPRESETEDITCANCEL = _descriptor.Descriptor(
  name='WSDK_RequestSetPresetEditCancel',
  full_name='wsdk_commands.WSDK_RequestSetPresetEditCancel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=251,
)


_WSDK_REQUESTSETPRESETEDITSTORE = _descriptor.Descriptor(
  name='WSDK_RequestSetPresetEditStore',
  full_name='wsdk_commands.WSDK_RequestSetPresetEditStore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=285,
)


_WSDK_REQUESTSETPRESETFACTORYRESET = _descriptor.Descriptor(
  name='WSDK_RequestSetPresetFactoryReset',
  full_name='wsdk_commands.WSDK_RequestSetPresetFactoryReset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preset_id', full_name='wsdk_commands.WSDK_RequestSetPresetFactoryReset.preset_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=341,
)


_WSDK_REQUESTSETPRESETREMOVE = _descriptor.Descriptor(
  name='WSDK_RequestSetPresetRemove',
  full_name='wsdk_commands.WSDK_RequestSetPresetRemove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preset_id', full_name='wsdk_commands.WSDK_RequestSetPresetRemove.preset_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=391,
)


_WSDK_REQUESTSETPRESETCREATE = _descriptor.Descriptor(
  name='WSDK_RequestSetPresetCreate',
  full_name='wsdk_commands.WSDK_RequestSetPresetCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_id', full_name='wsdk_commands.WSDK_RequestSetPresetCreate.group_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='wsdk_commands.WSDK_RequestSetPresetCreate.mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon', full_name='wsdk_commands.WSDK_RequestSetPresetCreate.icon', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title_id', full_name='wsdk_commands.WSDK_RequestSetPresetCreate.title_id', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title_number', full_name='wsdk_commands.WSDK_RequestSetPresetCreate.title_number', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=616,
)


_WSDK_REQUESTSETPRESETORDER = _descriptor.Descriptor(
  name='WSDK_RequestSetPresetOrder',
  full_name='wsdk_commands.WSDK_RequestSetPresetOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preset_id', full_name='wsdk_commands.WSDK_RequestSetPresetOrder.preset_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preset_order', full_name='wsdk_commands.WSDK_RequestSetPresetOrder.preset_order', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=687,
)

_WSDK_REQUESTSETPRESETCREATE.fields_by_name['mode'].enum_type = wsdkCommands_dot_WSDK__EnumFlatMode__pb2._WSDK_ENUMFLATMODE
_WSDK_REQUESTSETPRESETCREATE.fields_by_name['icon'].enum_type = wsdkCommands_dot_WSDK__EnumPresetIcon__pb2._WSDK_ENUMPRESETICON
_WSDK_REQUESTSETPRESETCREATE.fields_by_name['title_id'].enum_type = wsdkCommands_dot_WSDK__EnumPresetTitle__pb2._WSDK_ENUMPRESETTITLE
DESCRIPTOR.message_types_by_name['WSDK_RequestSetPresetEditStart'] = _WSDK_REQUESTSETPRESETEDITSTART
DESCRIPTOR.message_types_by_name['WSDK_RequestSetPresetEditCancel'] = _WSDK_REQUESTSETPRESETEDITCANCEL
DESCRIPTOR.message_types_by_name['WSDK_RequestSetPresetEditStore'] = _WSDK_REQUESTSETPRESETEDITSTORE
DESCRIPTOR.message_types_by_name['WSDK_RequestSetPresetFactoryReset'] = _WSDK_REQUESTSETPRESETFACTORYRESET
DESCRIPTOR.message_types_by_name['WSDK_RequestSetPresetRemove'] = _WSDK_REQUESTSETPRESETREMOVE
DESCRIPTOR.message_types_by_name['WSDK_RequestSetPresetCreate'] = _WSDK_REQUESTSETPRESETCREATE
DESCRIPTOR.message_types_by_name['WSDK_RequestSetPresetOrder'] = _WSDK_REQUESTSETPRESETORDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_RequestSetPresetEditStart = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetPresetEditStart', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETPRESETEDITSTART,
  '__module__' : 'WSDK_RequestSetPreset_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetPresetEditStart)
  })
_sym_db.RegisterMessage(WSDK_RequestSetPresetEditStart)

WSDK_RequestSetPresetEditCancel = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetPresetEditCancel', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETPRESETEDITCANCEL,
  '__module__' : 'WSDK_RequestSetPreset_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetPresetEditCancel)
  })
_sym_db.RegisterMessage(WSDK_RequestSetPresetEditCancel)

WSDK_RequestSetPresetEditStore = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetPresetEditStore', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETPRESETEDITSTORE,
  '__module__' : 'WSDK_RequestSetPreset_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetPresetEditStore)
  })
_sym_db.RegisterMessage(WSDK_RequestSetPresetEditStore)

WSDK_RequestSetPresetFactoryReset = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetPresetFactoryReset', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETPRESETFACTORYRESET,
  '__module__' : 'WSDK_RequestSetPreset_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetPresetFactoryReset)
  })
_sym_db.RegisterMessage(WSDK_RequestSetPresetFactoryReset)

WSDK_RequestSetPresetRemove = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetPresetRemove', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETPRESETREMOVE,
  '__module__' : 'WSDK_RequestSetPreset_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetPresetRemove)
  })
_sym_db.RegisterMessage(WSDK_RequestSetPresetRemove)

WSDK_RequestSetPresetCreate = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetPresetCreate', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETPRESETCREATE,
  '__module__' : 'WSDK_RequestSetPreset_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetPresetCreate)
  })
_sym_db.RegisterMessage(WSDK_RequestSetPresetCreate)

WSDK_RequestSetPresetOrder = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetPresetOrder', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETPRESETORDER,
  '__module__' : 'WSDK_RequestSetPreset_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetPresetOrder)
  })
_sym_db.RegisterMessage(WSDK_RequestSetPresetOrder)


# @@protoc_insertion_point(module_scope)
