# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_RequestSetShutter.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumShutter_pb2 as wsdkCommands_dot_WSDK__EnumShutter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_RequestSetShutter.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1cWSDK_RequestSetShutter.proto\x12\rwsdk_commands\x1a#wsdkCommands/WSDK_EnumShutter.proto\"J\n\x16WSDK_RequestSetShutter\x12\x30\n\x07shutter\x18\x01 \x02(\x0e\x32\x1f.wsdk_commands.WSDK_EnumShutter'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumShutter__pb2.DESCRIPTOR,])




_WSDK_REQUESTSETSHUTTER = _descriptor.Descriptor(
  name='WSDK_RequestSetShutter',
  full_name='wsdk_commands.WSDK_RequestSetShutter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shutter', full_name='wsdk_commands.WSDK_RequestSetShutter.shutter', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=158,
)

_WSDK_REQUESTSETSHUTTER.fields_by_name['shutter'].enum_type = wsdkCommands_dot_WSDK__EnumShutter__pb2._WSDK_ENUMSHUTTER
DESCRIPTOR.message_types_by_name['WSDK_RequestSetShutter'] = _WSDK_REQUESTSETSHUTTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_RequestSetShutter = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetShutter', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETSHUTTER,
  '__module__' : 'WSDK_RequestSetShutter_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetShutter)
  })
_sym_db.RegisterMessage(WSDK_RequestSetShutter)


# @@protoc_insertion_point(module_scope)
