# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_ResponseGetClientId.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from generic import EnumResultGeneric_pb2 as generic_dot_EnumResultGeneric__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_ResponseGetClientId.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1eWSDK_ResponseGetClientId.proto\x12\rwsdk_commands\x1a\x1fgeneric/EnumResultGeneric.proto\"_\n\x18WSDK_ResponseGetClientId\x12\x11\n\tclient_id\x18\x01 \x02(\t\x12\x30\n\x06result\x18\x02 \x02(\x0e\x32 .wsdk_commands.EnumResultGeneric'
  ,
  dependencies=[generic_dot_EnumResultGeneric__pb2.DESCRIPTOR,])




_WSDK_RESPONSEGETCLIENTID = _descriptor.Descriptor(
  name='WSDK_ResponseGetClientId',
  full_name='wsdk_commands.WSDK_ResponseGetClientId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='wsdk_commands.WSDK_ResponseGetClientId.client_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='wsdk_commands.WSDK_ResponseGetClientId.result', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=177,
)

_WSDK_RESPONSEGETCLIENTID.fields_by_name['result'].enum_type = generic_dot_EnumResultGeneric__pb2._ENUMRESULTGENERIC
DESCRIPTOR.message_types_by_name['WSDK_ResponseGetClientId'] = _WSDK_RESPONSEGETCLIENTID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_ResponseGetClientId = _reflection.GeneratedProtocolMessageType('WSDK_ResponseGetClientId', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_RESPONSEGETCLIENTID,
  '__module__' : 'WSDK_ResponseGetClientId_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_ResponseGetClientId)
  })
_sym_db.RegisterMessage(WSDK_ResponseGetClientId)


# @@protoc_insertion_point(module_scope)
