# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumRegisterOTAStatus.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumRegisterOTAStatus.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n-wsdkCommands/WSDK_EnumRegisterOTAStatus.proto\x12\rwsdk_commands*i\n\x1aWSDK_EnumRegisterOTAStatus\x12\"\n\x1eWSDK_REGISTER_OTA_STATUS_STATE\x10\x01\x12\'\n#WSDK_REGISTER_OTA_STATUS_PERCENTAGE\x10\x02'
)

_WSDK_ENUMREGISTEROTASTATUS = _descriptor.EnumDescriptor(
  name='WSDK_EnumRegisterOTAStatus',
  full_name='wsdk_commands.WSDK_EnumRegisterOTAStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_OTA_STATUS_STATE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_OTA_STATUS_PERCENTAGE', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=64,
  serialized_end=169,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMREGISTEROTASTATUS)

WSDK_EnumRegisterOTAStatus = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMREGISTEROTASTATUS)
WSDK_REGISTER_OTA_STATUS_STATE = 1
WSDK_REGISTER_OTA_STATUS_PERCENTAGE = 2


DESCRIPTOR.enum_types_by_name['WSDK_EnumRegisterOTAStatus'] = _WSDK_ENUMREGISTEROTASTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
