# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumCAHServer.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumCAHServer.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n%wsdkCommands/WSDK_EnumCAHServer.proto\x12\rwsdk_commands*i\n\x12WSDK_EnumCAHServer\x12\x1e\n\x1aWSDK_CAH_SERVER_PRODUCTION\x10\x00\x12\x1b\n\x17WSDK_CAH_SERVER_STAGING\x10\x01\x12\x16\n\x12WSDK_CAH_SERVER_QA\x10\x02'
)

_WSDK_ENUMCAHSERVER = _descriptor.EnumDescriptor(
  name='WSDK_EnumCAHServer',
  full_name='wsdk_commands.WSDK_EnumCAHServer',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAH_SERVER_PRODUCTION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAH_SERVER_STAGING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAH_SERVER_QA', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=56,
  serialized_end=161,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMCAHSERVER)

WSDK_EnumCAHServer = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMCAHSERVER)
WSDK_CAH_SERVER_PRODUCTION = 0
WSDK_CAH_SERVER_STAGING = 1
WSDK_CAH_SERVER_QA = 2


DESCRIPTOR.enum_types_by_name['WSDK_EnumCAHServer'] = _WSDK_ENUMCAHSERVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
