# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumFlatMode.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumFlatMode.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n$wsdkCommands/WSDK_EnumFlatMode.proto\x12\rwsdk_commands*\x9a\x04\n\x11WSDK_EnumFlatMode\x12#\n\x16WSDK_FLAT_MODE_UNKNOWN\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1b\n\x17WSDK_FLAT_MODE_PLAYBACK\x10\x04\x12\x18\n\x14WSDK_FLAT_MODE_SETUP\x10\x05\x12\x18\n\x14WSDK_FLAT_MODE_VIDEO\x10\x0c\x12#\n\x1fWSDK_FLAT_MODE_TIME_LAPSE_VIDEO\x10\r\x12\x1a\n\x16WSDK_FLAT_MODE_LOOPING\x10\x0f\x12\x18\n\x14WSDK_FLAT_MODE_PHOTO\x10\x11\x12\x1e\n\x1aWSDK_FLAT_MODE_PHOTO_NIGHT\x10\x12\x12\x1e\n\x1aWSDK_FLAT_MODE_PHOTO_BURST\x10\x13\x12#\n\x1fWSDK_FLAT_MODE_TIME_LAPSE_PHOTO\x10\x14\x12$\n WSDK_FLAT_MODE_NIGHT_LAPSE_PHOTO\x10\x15\x12&\n\"WSDK_FLAT_MODE_BROADCAST_BROADCAST\x10\x17\x12\"\n\x1eWSDK_FLAT_MODE_TIME_WARP_VIDEO\x10\x18\x12\x1d\n\x19WSDK_FLAT_MODE_LIVE_BURST\x10\x19\x12$\n WSDK_FLAT_MODE_NIGHT_LAPSE_VIDEO\x10\x1a\x12\x18\n\x14WSDK_FLAT_MODE_SLOMO\x10\x1b'
)

_WSDK_ENUMFLATMODE = _descriptor.EnumDescriptor(
  name='WSDK_EnumFlatMode',
  full_name='wsdk_commands.WSDK_EnumFlatMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_UNKNOWN', index=0, number=-1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_PLAYBACK', index=1, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_SETUP', index=2, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_VIDEO', index=3, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_TIME_LAPSE_VIDEO', index=4, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_LOOPING', index=5, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_PHOTO', index=6, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_PHOTO_NIGHT', index=7, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_PHOTO_BURST', index=8, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_TIME_LAPSE_PHOTO', index=9, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_NIGHT_LAPSE_PHOTO', index=10, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_BROADCAST_BROADCAST', index=11, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_TIME_WARP_VIDEO', index=12, number=24,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_LIVE_BURST', index=13, number=25,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_NIGHT_LAPSE_VIDEO', index=14, number=26,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_FLAT_MODE_SLOMO', index=15, number=27,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=56,
  serialized_end=594,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMFLATMODE)

WSDK_EnumFlatMode = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMFLATMODE)
WSDK_FLAT_MODE_UNKNOWN = -1
WSDK_FLAT_MODE_PLAYBACK = 4
WSDK_FLAT_MODE_SETUP = 5
WSDK_FLAT_MODE_VIDEO = 12
WSDK_FLAT_MODE_TIME_LAPSE_VIDEO = 13
WSDK_FLAT_MODE_LOOPING = 15
WSDK_FLAT_MODE_PHOTO = 17
WSDK_FLAT_MODE_PHOTO_NIGHT = 18
WSDK_FLAT_MODE_PHOTO_BURST = 19
WSDK_FLAT_MODE_TIME_LAPSE_PHOTO = 20
WSDK_FLAT_MODE_NIGHT_LAPSE_PHOTO = 21
WSDK_FLAT_MODE_BROADCAST_BROADCAST = 23
WSDK_FLAT_MODE_TIME_WARP_VIDEO = 24
WSDK_FLAT_MODE_LIVE_BURST = 25
WSDK_FLAT_MODE_NIGHT_LAPSE_VIDEO = 26
WSDK_FLAT_MODE_SLOMO = 27


DESCRIPTOR.enum_types_by_name['WSDK_EnumFlatMode'] = _WSDK_ENUMFLATMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
