# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumCameraWakeupReason.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumCameraWakeupReason.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n.wsdkCommands/WSDK_EnumCameraWakeupReason.proto\x12\rwsdk_commands*\xbc\x04\n\x1bWSDK_EnumCameraWakeupReason\x12*\n&WSDK_BOOT_REASON_POWER_ON_FROM_SCRATCH\x10\x00\x12\x1a\n\x16WSDK_BOOT_REASON_RESET\x10\x01\x12!\n\x1dWSDK_BOOT_REASON_POWER_BUTTON\x10\x02\x12#\n\x1fWSDK_BOOT_REASON_SHUTTER_BUTTON\x10\x03\x12$\n WSDK_BOOT_REASON_SETTINGS_BUTTON\x10\x04\x12!\n\x1dWSDK_BOOT_REASON_HEROBUS_WAKE\x10\x05\x12\x1e\n\x1aWSDK_BOOT_REASON_RTC_ALARM\x10\x06\x12$\n WSDK_BOOT_REASON_SDCARD_INSERTED\x10\x07\x12\"\n\x1eWSDK_BOOT_REASON_WIRELESS_WAKE\x10\x08\x12\x1d\n\x19WSDK_BOOT_REASON_BLE_WAKE\x10\t\x12\"\n\x1eWSDK_BOOT_REASON_USB1_INSERTED\x10\n\x12!\n\x1dWSDK_BOOT_REASON_USB1_REMOVED\x10\x0b\x12\"\n\x1eWSDK_BOOT_REASON_USB2_INSERTED\x10\x0c\x12!\n\x1dWSDK_BOOT_REASON_USB2_REMOVED\x10\r\x12-\n)WSDK_BOOT_REASON_DEPLETED_BOMBIE_ATTACHED\x10\x0e'
)

_WSDK_ENUMCAMERAWAKEUPREASON = _descriptor.EnumDescriptor(
  name='WSDK_EnumCameraWakeupReason',
  full_name='wsdk_commands.WSDK_EnumCameraWakeupReason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_POWER_ON_FROM_SCRATCH', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_RESET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_POWER_BUTTON', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_SHUTTER_BUTTON', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_SETTINGS_BUTTON', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_HEROBUS_WAKE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_RTC_ALARM', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_SDCARD_INSERTED', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_WIRELESS_WAKE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_BLE_WAKE', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_USB1_INSERTED', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_USB1_REMOVED', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_USB2_INSERTED', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_USB2_REMOVED', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_BOOT_REASON_DEPLETED_BOMBIE_ATTACHED', index=14, number=14,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=66,
  serialized_end=638,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMCAMERAWAKEUPREASON)

WSDK_EnumCameraWakeupReason = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMCAMERAWAKEUPREASON)
WSDK_BOOT_REASON_POWER_ON_FROM_SCRATCH = 0
WSDK_BOOT_REASON_RESET = 1
WSDK_BOOT_REASON_POWER_BUTTON = 2
WSDK_BOOT_REASON_SHUTTER_BUTTON = 3
WSDK_BOOT_REASON_SETTINGS_BUTTON = 4
WSDK_BOOT_REASON_HEROBUS_WAKE = 5
WSDK_BOOT_REASON_RTC_ALARM = 6
WSDK_BOOT_REASON_SDCARD_INSERTED = 7
WSDK_BOOT_REASON_WIRELESS_WAKE = 8
WSDK_BOOT_REASON_BLE_WAKE = 9
WSDK_BOOT_REASON_USB1_INSERTED = 10
WSDK_BOOT_REASON_USB1_REMOVED = 11
WSDK_BOOT_REASON_USB2_INSERTED = 12
WSDK_BOOT_REASON_USB2_REMOVED = 13
WSDK_BOOT_REASON_DEPLETED_BOMBIE_ATTACHED = 14


DESCRIPTOR.enum_types_by_name['WSDK_EnumCameraWakeupReason'] = _WSDK_ENUMCAMERAWAKEUPREASON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
