# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumShutter.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumShutter.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n#wsdkCommands/WSDK_EnumShutter.proto\x12\rwsdk_commands*=\n\x10WSDK_EnumShutter\x12\x14\n\x10WSDK_SHUTTER_OFF\x10\x00\x12\x13\n\x0fWSDK_SHUTTER_ON\x10\x01'
)

_WSDK_ENUMSHUTTER = _descriptor.EnumDescriptor(
  name='WSDK_EnumShutter',
  full_name='wsdk_commands.WSDK_EnumShutter',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_SHUTTER_OFF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_SHUTTER_ON', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=54,
  serialized_end=115,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMSHUTTER)

WSDK_EnumShutter = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMSHUTTER)
WSDK_SHUTTER_OFF = 0
WSDK_SHUTTER_ON = 1


DESCRIPTOR.enum_types_by_name['WSDK_EnumShutter'] = _WSDK_ENUMSHUTTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
