# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumPresetGroup.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumPresetGroup.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\'wsdkCommands/WSDK_EnumPresetGroup.proto\x12\rwsdk_commands*\xa5\x02\n\x14WSDK_EnumPresetGroup\x12\x1f\n\x1aWSDK_PRESET_GROUP_ID_VIDEO\x10\xe8\x07\x12\x1f\n\x1aWSDK_PRESET_GROUP_ID_PHOTO\x10\xe9\x07\x12#\n\x1eWSDK_PRESET_GROUP_ID_TIMELAPSE\x10\xea\x07\x12)\n$WSDK_PRESET_GROUP_ID_VIDEO_DUAL_LENS\x10\xeb\x07\x12)\n$WSDK_PRESET_GROUP_ID_PHOTO_DUAL_LENS\x10\xec\x07\x12-\n(WSDK_PRESET_GROUP_ID_TIMELAPSE_DUAL_LENS\x10\xed\x07\x12!\n\x1cWSDK_PRESET_GROUP_ID_SPECIAL\x10\xee\x07'
)

_WSDK_ENUMPRESETGROUP = _descriptor.EnumDescriptor(
  name='WSDK_EnumPresetGroup',
  full_name='wsdk_commands.WSDK_EnumPresetGroup',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_GROUP_ID_VIDEO', index=0, number=1000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_GROUP_ID_PHOTO', index=1, number=1001,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_GROUP_ID_TIMELAPSE', index=2, number=1002,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_GROUP_ID_VIDEO_DUAL_LENS', index=3, number=1003,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_GROUP_ID_PHOTO_DUAL_LENS', index=4, number=1004,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_GROUP_ID_TIMELAPSE_DUAL_LENS', index=5, number=1005,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_GROUP_ID_SPECIAL', index=6, number=1006,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=59,
  serialized_end=352,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMPRESETGROUP)

WSDK_EnumPresetGroup = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMPRESETGROUP)
WSDK_PRESET_GROUP_ID_VIDEO = 1000
WSDK_PRESET_GROUP_ID_PHOTO = 1001
WSDK_PRESET_GROUP_ID_TIMELAPSE = 1002
WSDK_PRESET_GROUP_ID_VIDEO_DUAL_LENS = 1003
WSDK_PRESET_GROUP_ID_PHOTO_DUAL_LENS = 1004
WSDK_PRESET_GROUP_ID_TIMELAPSE_DUAL_LENS = 1005
WSDK_PRESET_GROUP_ID_SPECIAL = 1006


DESCRIPTOR.enum_types_by_name['WSDK_EnumPresetGroup'] = _WSDK_ENUMPRESETGROUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
