# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumWindowSize.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumWindowSize.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n&wsdkCommands/WSDK_EnumWindowSize.proto\x12\rwsdk_commands*d\n\x13WSDK_EnumWindowSize\x12\x18\n\x14WSDK_WINDOW_SIZE_480\x10\x04\x12\x18\n\x14WSDK_WINDOW_SIZE_720\x10\x07\x12\x19\n\x15WSDK_WINDOW_SIZE_1080\x10\x0c'
)

_WSDK_ENUMWINDOWSIZE = _descriptor.EnumDescriptor(
  name='WSDK_EnumWindowSize',
  full_name='wsdk_commands.WSDK_EnumWindowSize',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_WINDOW_SIZE_480', index=0, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WINDOW_SIZE_720', index=1, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WINDOW_SIZE_1080', index=2, number=12,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=57,
  serialized_end=157,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMWINDOWSIZE)

WSDK_EnumWindowSize = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMWINDOWSIZE)
WSDK_WINDOW_SIZE_480 = 4
WSDK_WINDOW_SIZE_720 = 7
WSDK_WINDOW_SIZE_1080 = 12


DESCRIPTOR.enum_types_by_name['WSDK_EnumWindowSize'] = _WSDK_ENUMWINDOWSIZE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
