# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumCAHA.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumCAHA.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n wsdkCommands/WSDK_EnumCAHA.proto\x12\rwsdk_commands*\xea\x02\n\x12WSDK_EnumCAHAState\x12\x1c\n\x18WSDK_CAHA_STATE_INACTIVE\x10\x00\x12\"\n\x1eWSDK_CAHA_STATE_INTERNET_CHECK\x10\x01\x12&\n\"WSDK_CAHA_STATE_INTERNEY_CONNECTED\x10\x02\x12$\n WSDK_CAHA_STATE_CREDENTIAL_CHECK\x10\x03\x12\"\n\x1eWSDK_CAHA_STATE_ENTITLEMENT_OK\x10\x04\x12\x1d\n\x19WSDK_CAHA_STATE_UPLOADING\x10\x05\x12&\n\"WSDK_CAHA_STATE_UPLOADING_COMPLETE\x10\x06\x12!\n\x1dWSDK_CAHA_STATE_SHUTTING_DOWN\x10\x07\x12\x19\n\x15WSDK_CAHA_STATE_ERROR\x10\x08\x12\x1b\n\x17WSDK_CAHA_STATE_CSI_ERR\x10\x7f*\x96\x01\n\x10WSDK_EnumCAHACat\x12\x13\n\x0fWSDK_CAHA_CAT_0\x10\x00\x12\x13\n\x0fWSDK_CAHA_CAT_1\x10\x01\x12\x13\n\x0fWSDK_CAHA_CAT_2\x10\x02\x12\x13\n\x0fWSDK_CAHA_CAT_3\x10\x03\x12\x13\n\x0fWSDK_CAHA_CAT_4\x10\x04\x12\x19\n\x15WSDK_CAHA_CAT_CSI_ERR\x10\x7f*\x96\x01\n\x10WSDK_EnumCAHASub\x12\x13\n\x0fWSDK_CAHA_SUB_0\x10\x00\x12\x13\n\x0fWSDK_CAHA_SUB_1\x10\x01\x12\x13\n\x0fWSDK_CAHA_SUB_2\x10\x02\x12\x13\n\x0fWSDK_CAHA_SUB_3\x10\x03\x12\x13\n\x0fWSDK_CAHA_SUB_4\x10\x04\x12\x19\n\x15WSDK_CAHA_SUB_CSI_ERR\x10\x7f*\x96\x01\n\x10WSDK_EnumCAHAErr\x12\x13\n\x0fWSDK_CAHA_ERR_0\x10\x00\x12\x13\n\x0fWSDK_CAHA_ERR_1\x10\x01\x12\x13\n\x0fWSDK_CAHA_ERR_2\x10\x02\x12\x13\n\x0fWSDK_CAHA_ERR_3\x10\x03\x12\x13\n\x0fWSDK_CAHA_ERR_4\x10\x04\x12\x19\n\x15WSDK_CAHA_ERR_CSI_ERR\x10\x7f'
)

_WSDK_ENUMCAHASTATE = _descriptor.EnumDescriptor(
  name='WSDK_EnumCAHAState',
  full_name='wsdk_commands.WSDK_EnumCAHAState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_STATE_INACTIVE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_STATE_INTERNET_CHECK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_STATE_INTERNEY_CONNECTED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_STATE_CREDENTIAL_CHECK', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_STATE_ENTITLEMENT_OK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_STATE_UPLOADING', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_STATE_UPLOADING_COMPLETE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_STATE_SHUTTING_DOWN', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_STATE_ERROR', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_STATE_CSI_ERR', index=9, number=127,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=52,
  serialized_end=414,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMCAHASTATE)

WSDK_EnumCAHAState = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMCAHASTATE)
_WSDK_ENUMCAHACAT = _descriptor.EnumDescriptor(
  name='WSDK_EnumCAHACat',
  full_name='wsdk_commands.WSDK_EnumCAHACat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_CAT_0', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_CAT_1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_CAT_2', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_CAT_3', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_CAT_4', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_CAT_CSI_ERR', index=5, number=127,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=417,
  serialized_end=567,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMCAHACAT)

WSDK_EnumCAHACat = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMCAHACAT)
_WSDK_ENUMCAHASUB = _descriptor.EnumDescriptor(
  name='WSDK_EnumCAHASub',
  full_name='wsdk_commands.WSDK_EnumCAHASub',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_SUB_0', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_SUB_1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_SUB_2', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_SUB_3', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_SUB_4', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_SUB_CSI_ERR', index=5, number=127,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=570,
  serialized_end=720,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMCAHASUB)

WSDK_EnumCAHASub = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMCAHASUB)
_WSDK_ENUMCAHAERR = _descriptor.EnumDescriptor(
  name='WSDK_EnumCAHAErr',
  full_name='wsdk_commands.WSDK_EnumCAHAErr',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_ERR_0', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_ERR_1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_ERR_2', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_ERR_3', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_ERR_4', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_CAHA_ERR_CSI_ERR', index=5, number=127,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=723,
  serialized_end=873,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMCAHAERR)

WSDK_EnumCAHAErr = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMCAHAERR)
WSDK_CAHA_STATE_INACTIVE = 0
WSDK_CAHA_STATE_INTERNET_CHECK = 1
WSDK_CAHA_STATE_INTERNEY_CONNECTED = 2
WSDK_CAHA_STATE_CREDENTIAL_CHECK = 3
WSDK_CAHA_STATE_ENTITLEMENT_OK = 4
WSDK_CAHA_STATE_UPLOADING = 5
WSDK_CAHA_STATE_UPLOADING_COMPLETE = 6
WSDK_CAHA_STATE_SHUTTING_DOWN = 7
WSDK_CAHA_STATE_ERROR = 8
WSDK_CAHA_STATE_CSI_ERR = 127
WSDK_CAHA_CAT_0 = 0
WSDK_CAHA_CAT_1 = 1
WSDK_CAHA_CAT_2 = 2
WSDK_CAHA_CAT_3 = 3
WSDK_CAHA_CAT_4 = 4
WSDK_CAHA_CAT_CSI_ERR = 127
WSDK_CAHA_SUB_0 = 0
WSDK_CAHA_SUB_1 = 1
WSDK_CAHA_SUB_2 = 2
WSDK_CAHA_SUB_3 = 3
WSDK_CAHA_SUB_4 = 4
WSDK_CAHA_SUB_CSI_ERR = 127
WSDK_CAHA_ERR_0 = 0
WSDK_CAHA_ERR_1 = 1
WSDK_CAHA_ERR_2 = 2
WSDK_CAHA_ERR_3 = 3
WSDK_CAHA_ERR_4 = 4
WSDK_CAHA_ERR_CSI_ERR = 127


DESCRIPTOR.enum_types_by_name['WSDK_EnumCAHAState'] = _WSDK_ENUMCAHASTATE
DESCRIPTOR.enum_types_by_name['WSDK_EnumCAHACat'] = _WSDK_ENUMCAHACAT
DESCRIPTOR.enum_types_by_name['WSDK_EnumCAHASub'] = _WSDK_ENUMCAHASUB
DESCRIPTOR.enum_types_by_name['WSDK_EnumCAHAErr'] = _WSDK_ENUMCAHAERR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
