# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumPresetIcon.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumPresetIcon.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n&wsdkCommands/WSDK_EnumPresetIcon.proto\x12\rwsdk_commands*\xa0\x08\n\x13WSDK_EnumPresetIcon\x12\x1a\n\x16WSDK_PRESET_ICON_VIDEO\x10\x00\x12\x1d\n\x19WSDK_PRESET_ICON_ACTIVITY\x10\x01\x12\x1e\n\x1aWSDK_PRESET_ICON_CINEMATIC\x10\x02\x12\x1a\n\x16WSDK_PRESET_ICON_PHOTO\x10\x03\x12\x1f\n\x1bWSDK_PRESET_ICON_LIVE_BURST\x10\x04\x12\x1a\n\x16WSDK_PRESET_ICON_BURST\x10\x05\x12 \n\x1cWSDK_PRESET_ICON_PHOTO_NIGHT\x10\x06\x12\x1d\n\x19WSDK_PRESET_ICON_TIMEWARP\x10\x07\x12\x1e\n\x1aWSDK_PRESET_ICON_TIMELAPSE\x10\x08\x12\x1f\n\x1bWSDK_PRESET_ICON_NIGHTLAPSE\x10\t\x12\x1a\n\x16WSDK_PRESET_ICON_SNAIL\x10\n\x12\x1c\n\x18WSDK_PRESET_ICON_VIDEO_2\x10\x0b\x12\x1e\n\x1aWSDK_PRESET_ICON_360_VIDEO\x10\x0c\x12\x1c\n\x18WSDK_PRESET_ICON_PHOTO_2\x10\r\x12\x1d\n\x19WSDK_PRESET_ICON_PANORAMA\x10\x0e\x12\x1c\n\x18WSDK_PRESET_ICON_BURST_2\x10\x0f\x12\x1f\n\x1bWSDK_PRESET_ICON_TIMEWARP_2\x10\x10\x12 \n\x1cWSDK_PRESET_ICON_TIMELAPSE_2\x10\x11\x12\x1b\n\x17WSDK_PRESET_ICON_CUSTOM\x10\x12\x12\x18\n\x14WSDK_PRESET_ICON_AIR\x10\x13\x12\x19\n\x15WSDK_PRESET_ICON_BIKE\x10\x14\x12\x19\n\x15WSDK_PRESET_ICON_EPIC\x10\x15\x12\x1b\n\x17WSDK_PRESET_ICON_INDOOR\x10\x16\x12\x1a\n\x16WSDK_PRESET_ICON_MOTOR\x10\x17\x12\x1c\n\x18WSDK_PRESET_ICON_MOUNTED\x10\x18\x12\x1c\n\x18WSDK_PRESET_ICON_OUTDOOR\x10\x19\x12\x18\n\x14WSDK_PRESET_ICON_POV\x10\x1a\x12\x1b\n\x17WSDK_PRESET_ICON_SELFIE\x10\x1b\x12\x1a\n\x16WSDK_PRESET_ICON_SKATE\x10\x1c\x12\x19\n\x15WSDK_PRESET_ICON_SNOW\x10\x1d\x12\x1a\n\x16WSDK_PRESET_ICON_TRAIL\x10\x1e\x12\x1b\n\x17WSDK_PRESET_ICON_TRAVEL\x10\x1f\x12\x1a\n\x16WSDK_PRESET_ICON_WATER\x10 \x12\x1c\n\x18WSDK_PRESET_ICON_LOOPING\x10!\x12\x18\n\x14WSDK_PRESET_ICON_MAX\x10\"'
)

_WSDK_ENUMPRESETICON = _descriptor.EnumDescriptor(
  name='WSDK_EnumPresetIcon',
  full_name='wsdk_commands.WSDK_EnumPresetIcon',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_VIDEO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_ACTIVITY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_CINEMATIC', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_PHOTO', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_LIVE_BURST', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_BURST', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_PHOTO_NIGHT', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_TIMEWARP', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_TIMELAPSE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_NIGHTLAPSE', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_SNAIL', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_VIDEO_2', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_360_VIDEO', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_PHOTO_2', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_PANORAMA', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_BURST_2', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_TIMEWARP_2', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_TIMELAPSE_2', index=17, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_CUSTOM', index=18, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_AIR', index=19, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_BIKE', index=20, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_EPIC', index=21, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_INDOOR', index=22, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_MOTOR', index=23, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_MOUNTED', index=24, number=24,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_OUTDOOR', index=25, number=25,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_POV', index=26, number=26,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_SELFIE', index=27, number=27,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_SKATE', index=28, number=28,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_SNOW', index=29, number=29,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_TRAIL', index=30, number=30,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_TRAVEL', index=31, number=31,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_WATER', index=32, number=32,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_LOOPING', index=33, number=33,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_ICON_MAX', index=34, number=34,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=58,
  serialized_end=1114,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMPRESETICON)

WSDK_EnumPresetIcon = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMPRESETICON)
WSDK_PRESET_ICON_VIDEO = 0
WSDK_PRESET_ICON_ACTIVITY = 1
WSDK_PRESET_ICON_CINEMATIC = 2
WSDK_PRESET_ICON_PHOTO = 3
WSDK_PRESET_ICON_LIVE_BURST = 4
WSDK_PRESET_ICON_BURST = 5
WSDK_PRESET_ICON_PHOTO_NIGHT = 6
WSDK_PRESET_ICON_TIMEWARP = 7
WSDK_PRESET_ICON_TIMELAPSE = 8
WSDK_PRESET_ICON_NIGHTLAPSE = 9
WSDK_PRESET_ICON_SNAIL = 10
WSDK_PRESET_ICON_VIDEO_2 = 11
WSDK_PRESET_ICON_360_VIDEO = 12
WSDK_PRESET_ICON_PHOTO_2 = 13
WSDK_PRESET_ICON_PANORAMA = 14
WSDK_PRESET_ICON_BURST_2 = 15
WSDK_PRESET_ICON_TIMEWARP_2 = 16
WSDK_PRESET_ICON_TIMELAPSE_2 = 17
WSDK_PRESET_ICON_CUSTOM = 18
WSDK_PRESET_ICON_AIR = 19
WSDK_PRESET_ICON_BIKE = 20
WSDK_PRESET_ICON_EPIC = 21
WSDK_PRESET_ICON_INDOOR = 22
WSDK_PRESET_ICON_MOTOR = 23
WSDK_PRESET_ICON_MOUNTED = 24
WSDK_PRESET_ICON_OUTDOOR = 25
WSDK_PRESET_ICON_POV = 26
WSDK_PRESET_ICON_SELFIE = 27
WSDK_PRESET_ICON_SKATE = 28
WSDK_PRESET_ICON_SNOW = 29
WSDK_PRESET_ICON_TRAIL = 30
WSDK_PRESET_ICON_TRAVEL = 31
WSDK_PRESET_ICON_WATER = 32
WSDK_PRESET_ICON_LOOPING = 33
WSDK_PRESET_ICON_MAX = 34


DESCRIPTOR.enum_types_by_name['WSDK_EnumPresetIcon'] = _WSDK_ENUMPRESETICON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
