# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumRegisterLiveStreamStatus.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumRegisterLiveStreamStatus.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n4wsdkCommands/WSDK_EnumRegisterLiveStreamStatus.proto\x12\rwsdk_commands*\xd5\x01\n!WSDK_EnumRegisterLiveStreamStatus\x12+\n\'WSDK_REGISTER_LIVE_STREAM_STATUS_STATUS\x10\x01\x12*\n&WSDK_REGISTER_LIVE_STREAM_STATUS_ERROR\x10\x02\x12)\n%WSDK_REGISTER_LIVE_STREAM_STATUS_MODE\x10\x03\x12,\n(WSDK_REGISTER_LIVE_STREAM_STATUS_BITRATE\x10\x04'
)

_WSDK_ENUMREGISTERLIVESTREAMSTATUS = _descriptor.EnumDescriptor(
  name='WSDK_EnumRegisterLiveStreamStatus',
  full_name='wsdk_commands.WSDK_EnumRegisterLiveStreamStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_LIVE_STREAM_STATUS_STATUS', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_LIVE_STREAM_STATUS_ERROR', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_LIVE_STREAM_STATUS_MODE', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_LIVE_STREAM_STATUS_BITRATE', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=72,
  serialized_end=285,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMREGISTERLIVESTREAMSTATUS)

WSDK_EnumRegisterLiveStreamStatus = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMREGISTERLIVESTREAMSTATUS)
WSDK_REGISTER_LIVE_STREAM_STATUS_STATUS = 1
WSDK_REGISTER_LIVE_STREAM_STATUS_ERROR = 2
WSDK_REGISTER_LIVE_STREAM_STATUS_MODE = 3
WSDK_REGISTER_LIVE_STREAM_STATUS_BITRATE = 4


DESCRIPTOR.enum_types_by_name['WSDK_EnumRegisterLiveStreamStatus'] = _WSDK_ENUMREGISTERLIVESTREAMSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
