# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_RequestSetOTAUpdate.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumOTACmd_pb2 as wsdkCommands_dot_WSDK__EnumOTACmd__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_RequestSetOTAUpdate.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1eWSDK_RequestSetOTAUpdate.proto\x12\rwsdk_commands\x1a\"wsdkCommands/WSDK_EnumOTACmd.proto\"K\n\x18WSDK_RequestSetOTAUpdate\x12/\n\x07ota_cmd\x18\x01 \x01(\x0e\x32\x1e.wsdk_commands.WSDK_EnumOTACmd'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumOTACmd__pb2.DESCRIPTOR,])




_WSDK_REQUESTSETOTAUPDATE = _descriptor.Descriptor(
  name='WSDK_RequestSetOTAUpdate',
  full_name='wsdk_commands.WSDK_RequestSetOTAUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ota_cmd', full_name='wsdk_commands.WSDK_RequestSetOTAUpdate.ota_cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=160,
)

_WSDK_REQUESTSETOTAUPDATE.fields_by_name['ota_cmd'].enum_type = wsdkCommands_dot_WSDK__EnumOTACmd__pb2._WSDK_ENUMOTACMD
DESCRIPTOR.message_types_by_name['WSDK_RequestSetOTAUpdate'] = _WSDK_REQUESTSETOTAUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_RequestSetOTAUpdate = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetOTAUpdate', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETOTAUPDATE,
  '__module__' : 'WSDK_RequestSetOTAUpdate_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetOTAUpdate)
  })
_sym_db.RegisterMessage(WSDK_RequestSetOTAUpdate)


# @@protoc_insertion_point(module_scope)
