# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_ResponseGetMobileOffloadState.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from generic import EnumResultGeneric_pb2 as generic_dot_EnumResultGeneric__pb2
from wsdkCommands import WSDK_EnumCameraWakeupReason_pb2 as wsdkCommands_dot_WSDK__EnumCameraWakeupReason__pb2
from wsdkCommands import WSDK_EnumSystemNotifyEvent_pb2 as wsdkCommands_dot_WSDK__EnumSystemNotifyEvent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_ResponseGetMobileOffloadState.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n(WSDK_ResponseGetMobileOffloadState.proto\x12\rwsdk_commands\x1a\x1fgeneric/EnumResultGeneric.proto\x1a.wsdkCommands/WSDK_EnumCameraWakeupReason.proto\x1a-wsdkCommands/WSDK_EnumSystemNotifyEvent.proto\"\xb9\x03\n\"WSDK_ResponseGetMobileOffloadState\x12\x30\n\x06result\x18\x01 \x02(\x0e\x32 .wsdk_commands.EnumResultGeneric\x12\x1c\n\x14mobile_offload_state\x18\x02 \x02(\x08\x12\x1b\n\x13new_media_available\x18\x03 \x02(\x08\x12\x12\n\nbattery_ok\x18\x04 \x02(\x08\x12\x12\n\nsd_card_ok\x18\x05 \x02(\x08\x12\x13\n\x0b\x63\x61mera_busy\x18\x06 \x02(\x08\x12\x11\n\tst_paused\x18\x07 \x02(\x08\x12\x18\n\x10\x63nt_this_boot_bt\x18\x08 \x01(\x05\x12\x18\n\x10\x63nt_this_boot_rc\x18\t \x01(\x05\x12\x18\n\x10\x63nt_this_boot_ap\x18\n \x01(\x05\x12H\n\x14\x63\x61mera_wakeup_reason\x18\x0b \x01(\x0e\x32*.wsdk_commands.WSDK_EnumCameraWakeupReason\x12>\n\x0bst_activity\x18\x0c \x01(\x0e\x32).wsdk_commands.WSDK_EnumSystemNotifyEvent'
  ,
  dependencies=[generic_dot_EnumResultGeneric__pb2.DESCRIPTOR,wsdkCommands_dot_WSDK__EnumCameraWakeupReason__pb2.DESCRIPTOR,wsdkCommands_dot_WSDK__EnumSystemNotifyEvent__pb2.DESCRIPTOR,])




_WSDK_RESPONSEGETMOBILEOFFLOADSTATE = _descriptor.Descriptor(
  name='WSDK_ResponseGetMobileOffloadState',
  full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.result', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobile_offload_state', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.mobile_offload_state', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_media_available', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.new_media_available', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery_ok', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.battery_ok', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sd_card_ok', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.sd_card_ok', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_busy', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.camera_busy', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='st_paused', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.st_paused', index=6,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cnt_this_boot_bt', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.cnt_this_boot_bt', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cnt_this_boot_rc', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.cnt_this_boot_rc', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cnt_this_boot_ap', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.cnt_this_boot_ap', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_wakeup_reason', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.camera_wakeup_reason', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='st_activity', full_name='wsdk_commands.WSDK_ResponseGetMobileOffloadState.st_activity', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=629,
)

_WSDK_RESPONSEGETMOBILEOFFLOADSTATE.fields_by_name['result'].enum_type = generic_dot_EnumResultGeneric__pb2._ENUMRESULTGENERIC
_WSDK_RESPONSEGETMOBILEOFFLOADSTATE.fields_by_name['camera_wakeup_reason'].enum_type = wsdkCommands_dot_WSDK__EnumCameraWakeupReason__pb2._WSDK_ENUMCAMERAWAKEUPREASON
_WSDK_RESPONSEGETMOBILEOFFLOADSTATE.fields_by_name['st_activity'].enum_type = wsdkCommands_dot_WSDK__EnumSystemNotifyEvent__pb2._WSDK_ENUMSYSTEMNOTIFYEVENT
DESCRIPTOR.message_types_by_name['WSDK_ResponseGetMobileOffloadState'] = _WSDK_RESPONSEGETMOBILEOFFLOADSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_ResponseGetMobileOffloadState = _reflection.GeneratedProtocolMessageType('WSDK_ResponseGetMobileOffloadState', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_RESPONSEGETMOBILEOFFLOADSTATE,
  '__module__' : 'WSDK_ResponseGetMobileOffloadState_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_ResponseGetMobileOffloadState)
  })
_sym_db.RegisterMessage(WSDK_ResponseGetMobileOffloadState)


# @@protoc_insertion_point(module_scope)
