# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_RequestClearNewMediaFlag.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_RequestClearNewMediaFlag.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n#WSDK_RequestClearNewMediaFlag.proto\x12\rwsdk_commands\"\x1f\n\x1dWSDK_RequestClearNewMediaFlag'
)




_WSDK_REQUESTCLEARNEWMEDIAFLAG = _descriptor.Descriptor(
  name='WSDK_RequestClearNewMediaFlag',
  full_name='wsdk_commands.WSDK_RequestClearNewMediaFlag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['WSDK_RequestClearNewMediaFlag'] = _WSDK_REQUESTCLEARNEWMEDIAFLAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_RequestClearNewMediaFlag = _reflection.GeneratedProtocolMessageType('WSDK_RequestClearNewMediaFlag', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTCLEARNEWMEDIAFLAG,
  '__module__' : 'WSDK_RequestClearNewMediaFlag_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestClearNewMediaFlag)
  })
_sym_db.RegisterMessage(WSDK_RequestClearNewMediaFlag)


# @@protoc_insertion_point(module_scope)
