# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_NotifyLiveStreamStatus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumLiveStreamStatus_pb2 as wsdkCommands_dot_WSDK__EnumLiveStreamStatus__pb2
from wsdkCommands import WSDK_EnumLiveStreamError_pb2 as wsdkCommands_dot_WSDK__EnumLiveStreamError__pb2
from wsdkCommands import WSDK_EnumWindowSize_pb2 as wsdkCommands_dot_WSDK__EnumWindowSize__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_NotifyLiveStreamStatus.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n!WSDK_NotifyLiveStreamStatus.proto\x12\rwsdk_commands\x1a,wsdkCommands/WSDK_EnumLiveStreamStatus.proto\x1a+wsdkCommands/WSDK_EnumLiveStreamError.proto\x1a&wsdkCommands/WSDK_EnumWindowSize.proto\"\xdb\x02\n\x1bWSDK_NotifyLiveStreamStatus\x12\x44\n\x12live_stream_status\x18\x01 \x01(\x0e\x32(.wsdk_commands.WSDK_EnumLiveStreamStatus\x12\x42\n\x11live_stream_error\x18\x02 \x01(\x0e\x32\'.wsdk_commands.WSDK_EnumLiveStreamError\x12\x1a\n\x12live_stream_encode\x18\x03 \x01(\x08\x12\x1b\n\x13live_stream_bitrate\x18\x04 \x01(\x05\x12S\n\'live_stream_window_size_supported_array\x18\x05 \x03(\x0e\x32\".wsdk_commands.WSDK_EnumWindowSize\x12$\n\x1clive_stream_encode_supported\x18\x06 \x01(\x08'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumLiveStreamStatus__pb2.DESCRIPTOR,wsdkCommands_dot_WSDK__EnumLiveStreamError__pb2.DESCRIPTOR,wsdkCommands_dot_WSDK__EnumWindowSize__pb2.DESCRIPTOR,])




_WSDK_NOTIFYLIVESTREAMSTATUS = _descriptor.Descriptor(
  name='WSDK_NotifyLiveStreamStatus',
  full_name='wsdk_commands.WSDK_NotifyLiveStreamStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='live_stream_status', full_name='wsdk_commands.WSDK_NotifyLiveStreamStatus.live_stream_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='live_stream_error', full_name='wsdk_commands.WSDK_NotifyLiveStreamStatus.live_stream_error', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='live_stream_encode', full_name='wsdk_commands.WSDK_NotifyLiveStreamStatus.live_stream_encode', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='live_stream_bitrate', full_name='wsdk_commands.WSDK_NotifyLiveStreamStatus.live_stream_bitrate', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='live_stream_window_size_supported_array', full_name='wsdk_commands.WSDK_NotifyLiveStreamStatus.live_stream_window_size_supported_array', index=4,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='live_stream_encode_supported', full_name='wsdk_commands.WSDK_NotifyLiveStreamStatus.live_stream_encode_supported', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=531,
)

_WSDK_NOTIFYLIVESTREAMSTATUS.fields_by_name['live_stream_status'].enum_type = wsdkCommands_dot_WSDK__EnumLiveStreamStatus__pb2._WSDK_ENUMLIVESTREAMSTATUS
_WSDK_NOTIFYLIVESTREAMSTATUS.fields_by_name['live_stream_error'].enum_type = wsdkCommands_dot_WSDK__EnumLiveStreamError__pb2._WSDK_ENUMLIVESTREAMERROR
_WSDK_NOTIFYLIVESTREAMSTATUS.fields_by_name['live_stream_window_size_supported_array'].enum_type = wsdkCommands_dot_WSDK__EnumWindowSize__pb2._WSDK_ENUMWINDOWSIZE
DESCRIPTOR.message_types_by_name['WSDK_NotifyLiveStreamStatus'] = _WSDK_NOTIFYLIVESTREAMSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_NotifyLiveStreamStatus = _reflection.GeneratedProtocolMessageType('WSDK_NotifyLiveStreamStatus', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_NOTIFYLIVESTREAMSTATUS,
  '__module__' : 'WSDK_NotifyLiveStreamStatus_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_NotifyLiveStreamStatus)
  })
_sym_db.RegisterMessage(WSDK_NotifyLiveStreamStatus)


# @@protoc_insertion_point(module_scope)
