# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_RequestSetBandSelect.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumBandSelect_pb2 as wsdkCommands_dot_WSDK__EnumBandSelect__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_RequestSetBandSelect.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1fWSDK_RequestSetBandSelect.proto\x12\rwsdk_commands\x1a&wsdkCommands/WSDK_EnumBandSelect.proto\"T\n\x19WSDK_RequestSetBandSelect\x12\x37\n\x0b\x62\x61nd_select\x18\x01 \x02(\x0e\x32\".wsdk_commands.WSDK_EnumBandSelect'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumBandSelect__pb2.DESCRIPTOR,])




_WSDK_REQUESTSETBANDSELECT = _descriptor.Descriptor(
  name='WSDK_RequestSetBandSelect',
  full_name='wsdk_commands.WSDK_RequestSetBandSelect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='band_select', full_name='wsdk_commands.WSDK_RequestSetBandSelect.band_select', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=174,
)

_WSDK_REQUESTSETBANDSELECT.fields_by_name['band_select'].enum_type = wsdkCommands_dot_WSDK__EnumBandSelect__pb2._WSDK_ENUMBANDSELECT
DESCRIPTOR.message_types_by_name['WSDK_RequestSetBandSelect'] = _WSDK_REQUESTSETBANDSELECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_RequestSetBandSelect = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetBandSelect', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETBANDSELECT,
  '__module__' : 'WSDK_RequestSetBandSelect_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetBandSelect)
  })
_sym_db.RegisterMessage(WSDK_RequestSetBandSelect)


# @@protoc_insertion_point(module_scope)
