# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_RequestSetCAHServer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumCAHServer_pb2 as wsdkCommands_dot_WSDK__EnumCAHServer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_RequestSetCAHServer.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1eWSDK_RequestSetCAHServer.proto\x12\rwsdk_commands\x1a%wsdkCommands/WSDK_EnumCAHServer.proto\"Q\n\x18WSDK_RequestSetCAHServer\x12\x35\n\ncah_server\x18\x01 \x02(\x0e\x32!.wsdk_commands.WSDK_EnumCAHServer'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumCAHServer__pb2.DESCRIPTOR,])




_WSDK_REQUESTSETCAHSERVER = _descriptor.Descriptor(
  name='WSDK_RequestSetCAHServer',
  full_name='wsdk_commands.WSDK_RequestSetCAHServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cah_server', full_name='wsdk_commands.WSDK_RequestSetCAHServer.cah_server', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=169,
)

_WSDK_REQUESTSETCAHSERVER.fields_by_name['cah_server'].enum_type = wsdkCommands_dot_WSDK__EnumCAHServer__pb2._WSDK_ENUMCAHSERVER
DESCRIPTOR.message_types_by_name['WSDK_RequestSetCAHServer'] = _WSDK_REQUESTSETCAHSERVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_RequestSetCAHServer = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetCAHServer', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETCAHSERVER,
  '__module__' : 'WSDK_RequestSetCAHServer_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetCAHServer)
  })
_sym_db.RegisterMessage(WSDK_RequestSetCAHServer)


# @@protoc_insertion_point(module_scope)
