# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_NotifyPresetStatus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_PresetGroup_pb2 as wsdkCommands_dot_WSDK__PresetGroup__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_NotifyPresetStatus.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1dWSDK_NotifyPresetStatus.proto\x12\rwsdk_commands\x1a#wsdkCommands/WSDK_PresetGroup.proto\"V\n\x17WSDK_NotifyPresetStatus\x12;\n\x12preset_group_array\x18\x01 \x03(\x0b\x32\x1f.wsdk_commands.WSDK_PresetGroup'
  ,
  dependencies=[wsdkCommands_dot_WSDK__PresetGroup__pb2.DESCRIPTOR,])




_WSDK_NOTIFYPRESETSTATUS = _descriptor.Descriptor(
  name='WSDK_NotifyPresetStatus',
  full_name='wsdk_commands.WSDK_NotifyPresetStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preset_group_array', full_name='wsdk_commands.WSDK_NotifyPresetStatus.preset_group_array', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=171,
)

_WSDK_NOTIFYPRESETSTATUS.fields_by_name['preset_group_array'].message_type = wsdkCommands_dot_WSDK__PresetGroup__pb2._WSDK_PRESETGROUP
DESCRIPTOR.message_types_by_name['WSDK_NotifyPresetStatus'] = _WSDK_NOTIFYPRESETSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_NotifyPresetStatus = _reflection.GeneratedProtocolMessageType('WSDK_NotifyPresetStatus', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_NOTIFYPRESETSTATUS,
  '__module__' : 'WSDK_NotifyPresetStatus_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_NotifyPresetStatus)
  })
_sym_db.RegisterMessage(WSDK_NotifyPresetStatus)


# @@protoc_insertion_point(module_scope)
