# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_RequestSetSystemNotifyEvent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumSystemNotifyEvent_pb2 as wsdkCommands_dot_WSDK__EnumSystemNotifyEvent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_RequestSetSystemNotifyEvent.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n&WSDK_RequestSetSystemNotifyEvent.proto\x12\rwsdk_commands\x1a-wsdkCommands/WSDK_EnumSystemNotifyEvent.proto\"c\n WSDK_RequestSetSystemNotifyEvent\x12?\n\x0cnotify_event\x18\x01 \x02(\x0e\x32).wsdk_commands.WSDK_EnumSystemNotifyEvent'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumSystemNotifyEvent__pb2.DESCRIPTOR,])




_WSDK_REQUESTSETSYSTEMNOTIFYEVENT = _descriptor.Descriptor(
  name='WSDK_RequestSetSystemNotifyEvent',
  full_name='wsdk_commands.WSDK_RequestSetSystemNotifyEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notify_event', full_name='wsdk_commands.WSDK_RequestSetSystemNotifyEvent.notify_event', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=203,
)

_WSDK_REQUESTSETSYSTEMNOTIFYEVENT.fields_by_name['notify_event'].enum_type = wsdkCommands_dot_WSDK__EnumSystemNotifyEvent__pb2._WSDK_ENUMSYSTEMNOTIFYEVENT
DESCRIPTOR.message_types_by_name['WSDK_RequestSetSystemNotifyEvent'] = _WSDK_REQUESTSETSYSTEMNOTIFYEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_RequestSetSystemNotifyEvent = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetSystemNotifyEvent', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETSYSTEMNOTIFYEVENT,
  '__module__' : 'WSDK_RequestSetSystemNotifyEvent_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetSystemNotifyEvent)
  })
_sym_db.RegisterMessage(WSDK_RequestSetSystemNotifyEvent)


# @@protoc_insertion_point(module_scope)
