# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_ResponseGetAssociationState.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumAssociationState_pb2 as wsdkCommands_dot_WSDK__EnumAssociationState__pb2
from generic import EnumResultGeneric_pb2 as generic_dot_EnumResultGeneric__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_ResponseGetAssociationState.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n&WSDK_ResponseGetAssociationState.proto\x12\rwsdk_commands\x1a,wsdkCommands/WSDK_EnumAssociationState.proto\x1a\x1fgeneric/EnumResultGeneric.proto\"\x99\x01\n WSDK_ResponseGetAssociationState\x12\x43\n\x11\x61ssociation_state\x18\x01 \x02(\x0e\x32(.wsdk_commands.WSDK_EnumAssociationState\x12\x30\n\x06result\x18\x02 \x02(\x0e\x32 .wsdk_commands.EnumResultGeneric'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumAssociationState__pb2.DESCRIPTOR,generic_dot_EnumResultGeneric__pb2.DESCRIPTOR,])




_WSDK_RESPONSEGETASSOCIATIONSTATE = _descriptor.Descriptor(
  name='WSDK_ResponseGetAssociationState',
  full_name='wsdk_commands.WSDK_ResponseGetAssociationState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='association_state', full_name='wsdk_commands.WSDK_ResponseGetAssociationState.association_state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='wsdk_commands.WSDK_ResponseGetAssociationState.result', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=290,
)

_WSDK_RESPONSEGETASSOCIATIONSTATE.fields_by_name['association_state'].enum_type = wsdkCommands_dot_WSDK__EnumAssociationState__pb2._WSDK_ENUMASSOCIATIONSTATE
_WSDK_RESPONSEGETASSOCIATIONSTATE.fields_by_name['result'].enum_type = generic_dot_EnumResultGeneric__pb2._ENUMRESULTGENERIC
DESCRIPTOR.message_types_by_name['WSDK_ResponseGetAssociationState'] = _WSDK_RESPONSEGETASSOCIATIONSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_ResponseGetAssociationState = _reflection.GeneratedProtocolMessageType('WSDK_ResponseGetAssociationState', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_RESPONSEGETASSOCIATIONSTATE,
  '__module__' : 'WSDK_ResponseGetAssociationState_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_ResponseGetAssociationState)
  })
_sym_db.RegisterMessage(WSDK_ResponseGetAssociationState)


# @@protoc_insertion_point(module_scope)
