# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: other/generic/EnumResultGeneric.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='other/generic/EnumResultGeneric.proto',
  package='generic',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n%other/generic/EnumResultGeneric.proto\x12\x07generic*\xac\x01\n\x11\x45numResultGeneric\x12\x12\n\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n\x0eRESULT_SUCCESS\x10\x01\x12\x15\n\x11RESULT_ILL_FORMED\x10\x02\x12\x18\n\x14RESULT_NOT_SUPPORTED\x10\x03\x12!\n\x1dRESULT_ARGUMENT_OUT_OF_BOUNDS\x10\x04\x12\x1b\n\x17RESULT_ARGUMENT_INVALID\x10\x05'
)

_ENUMRESULTGENERIC = _descriptor.EnumDescriptor(
  name='EnumResultGeneric',
  full_name='generic.EnumResultGeneric',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESULT_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESULT_SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESULT_ILL_FORMED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESULT_NOT_SUPPORTED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESULT_ARGUMENT_OUT_OF_BOUNDS', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESULT_ARGUMENT_INVALID', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=51,
  serialized_end=223,
)
_sym_db.RegisterEnumDescriptor(_ENUMRESULTGENERIC)

EnumResultGeneric = enum_type_wrapper.EnumTypeWrapper(_ENUMRESULTGENERIC)
RESULT_UNKNOWN = 0
RESULT_SUCCESS = 1
RESULT_ILL_FORMED = 2
RESULT_NOT_SUPPORTED = 3
RESULT_ARGUMENT_OUT_OF_BOUNDS = 4
RESULT_ARGUMENT_INVALID = 5


DESCRIPTOR.enum_types_by_name['EnumResultGeneric'] = _ENUMRESULTGENERIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
