# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: other/ResponseGeneric.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from other.generic import EnumResultGeneric_pb2 as other_dot_generic_dot_EnumResultGeneric__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='other/ResponseGeneric.proto',
  package='generic',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1bother/ResponseGeneric.proto\x12\x07generic\x1a%other/generic/EnumResultGeneric.proto\"=\n\x0fResponseGeneric\x12*\n\x06result\x18\x01 \x02(\x0e\x32\x1a.generic.EnumResultGeneric'
  ,
  dependencies=[other_dot_generic_dot_EnumResultGeneric__pb2.DESCRIPTOR,])




_RESPONSEGENERIC = _descriptor.Descriptor(
  name='ResponseGeneric',
  full_name='generic.ResponseGeneric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='generic.ResponseGeneric.result', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=140,
)

_RESPONSEGENERIC.fields_by_name['result'].enum_type = other_dot_generic_dot_EnumResultGeneric__pb2._ENUMRESULTGENERIC
DESCRIPTOR.message_types_by_name['ResponseGeneric'] = _RESPONSEGENERIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseGeneric = _reflection.GeneratedProtocolMessageType('ResponseGeneric', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEGENERIC,
  '__module__' : 'other.ResponseGeneric_pb2'
  # @@protoc_insertion_point(class_scope:generic.ResponseGeneric)
  })
_sym_db.RegisterMessage(ResponseGeneric)


# @@protoc_insertion_point(module_scope)
