# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_RequestGetLiveStreamStatus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumRegisterLiveStreamStatus_pb2 as wsdkCommands_dot_WSDK__EnumRegisterLiveStreamStatus__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_RequestGetLiveStreamStatus.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n%WSDK_RequestGetLiveStreamStatus.proto\x12\rwsdk_commands\x1a\x34wsdkCommands/WSDK_EnumRegisterLiveStreamStatus.proto\"\xd1\x01\n\x1fWSDK_RequestGetLiveStreamStatus\x12U\n\x1bregister_live_stream_status\x18\x01 \x03(\x0e\x32\x30.wsdk_commands.WSDK_EnumRegisterLiveStreamStatus\x12W\n\x1dunregister_live_stream_status\x18\x02 \x03(\x0e\x32\x30.wsdk_commands.WSDK_EnumRegisterLiveStreamStatus'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumRegisterLiveStreamStatus__pb2.DESCRIPTOR,])




_WSDK_REQUESTGETLIVESTREAMSTATUS = _descriptor.Descriptor(
  name='WSDK_RequestGetLiveStreamStatus',
  full_name='wsdk_commands.WSDK_RequestGetLiveStreamStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='register_live_stream_status', full_name='wsdk_commands.WSDK_RequestGetLiveStreamStatus.register_live_stream_status', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unregister_live_stream_status', full_name='wsdk_commands.WSDK_RequestGetLiveStreamStatus.unregister_live_stream_status', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=320,
)

_WSDK_REQUESTGETLIVESTREAMSTATUS.fields_by_name['register_live_stream_status'].enum_type = wsdkCommands_dot_WSDK__EnumRegisterLiveStreamStatus__pb2._WSDK_ENUMREGISTERLIVESTREAMSTATUS
_WSDK_REQUESTGETLIVESTREAMSTATUS.fields_by_name['unregister_live_stream_status'].enum_type = wsdkCommands_dot_WSDK__EnumRegisterLiveStreamStatus__pb2._WSDK_ENUMREGISTERLIVESTREAMSTATUS
DESCRIPTOR.message_types_by_name['WSDK_RequestGetLiveStreamStatus'] = _WSDK_REQUESTGETLIVESTREAMSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_RequestGetLiveStreamStatus = _reflection.GeneratedProtocolMessageType('WSDK_RequestGetLiveStreamStatus', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTGETLIVESTREAMSTATUS,
  '__module__' : 'WSDK_RequestGetLiveStreamStatus_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestGetLiveStreamStatus)
  })
_sym_db.RegisterMessage(WSDK_RequestGetLiveStreamStatus)


# @@protoc_insertion_point(module_scope)
