# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_RequestGetAssociationState.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_RequestGetAssociationState.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n%WSDK_RequestGetAssociationState.proto\x12\rwsdk_commands\"8\n\x1fWSDK_RequestGetAssociationState\x12\x15\n\rgopro_user_id\x18\x01 \x01(\t'
)




_WSDK_REQUESTGETASSOCIATIONSTATE = _descriptor.Descriptor(
  name='WSDK_RequestGetAssociationState',
  full_name='wsdk_commands.WSDK_RequestGetAssociationState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gopro_user_id', full_name='wsdk_commands.WSDK_RequestGetAssociationState.gopro_user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['WSDK_RequestGetAssociationState'] = _WSDK_REQUESTGETASSOCIATIONSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_RequestGetAssociationState = _reflection.GeneratedProtocolMessageType('WSDK_RequestGetAssociationState', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTGETASSOCIATIONSTATE,
  '__module__' : 'WSDK_RequestGetAssociationState_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestGetAssociationState)
  })
_sym_db.RegisterMessage(WSDK_RequestGetAssociationState)


# @@protoc_insertion_point(module_scope)
