# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_RequestSetLiveStreamMode.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumWindowSize_pb2 as wsdkCommands_dot_WSDK__EnumWindowSize__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_RequestSetLiveStreamMode.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n#WSDK_RequestSetLiveStreamMode.proto\x12\rwsdk_commands\x1a&wsdkCommands/WSDK_EnumWindowSize.proto\"\xa3\x01\n\x1dWSDK_RequestSetLiveStreamMode\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06\x65ncode\x18\x02 \x01(\x08\x12\x37\n\x0bwindow_size\x18\x03 \x01(\x0e\x32\".wsdk_commands.WSDK_EnumWindowSize\x12\x0e\n\x06token1\x18\x04 \x01(\t\x12\x0e\n\x06token2\x18\x05 \x01(\t\x12\x0c\n\x04\x63\x65rt\x18\x06 \x01(\x0c'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumWindowSize__pb2.DESCRIPTOR,])




_WSDK_REQUESTSETLIVESTREAMMODE = _descriptor.Descriptor(
  name='WSDK_RequestSetLiveStreamMode',
  full_name='wsdk_commands.WSDK_RequestSetLiveStreamMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='wsdk_commands.WSDK_RequestSetLiveStreamMode.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encode', full_name='wsdk_commands.WSDK_RequestSetLiveStreamMode.encode', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='window_size', full_name='wsdk_commands.WSDK_RequestSetLiveStreamMode.window_size', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token1', full_name='wsdk_commands.WSDK_RequestSetLiveStreamMode.token1', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token2', full_name='wsdk_commands.WSDK_RequestSetLiveStreamMode.token2', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cert', full_name='wsdk_commands.WSDK_RequestSetLiveStreamMode.cert', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=258,
)

_WSDK_REQUESTSETLIVESTREAMMODE.fields_by_name['window_size'].enum_type = wsdkCommands_dot_WSDK__EnumWindowSize__pb2._WSDK_ENUMWINDOWSIZE
DESCRIPTOR.message_types_by_name['WSDK_RequestSetLiveStreamMode'] = _WSDK_REQUESTSETLIVESTREAMMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_RequestSetLiveStreamMode = _reflection.GeneratedProtocolMessageType('WSDK_RequestSetLiveStreamMode', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTSETLIVESTREAMMODE,
  '__module__' : 'WSDK_RequestSetLiveStreamMode_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestSetLiveStreamMode)
  })
_sym_db.RegisterMessage(WSDK_RequestSetLiveStreamMode)


# @@protoc_insertion_point(module_scope)
