# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_NotifyOTAStatus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumOTAState_pb2 as wsdkCommands_dot_WSDK__EnumOTAState__pb2
from wsdkCommands import WSDK_EnumOTAError_pb2 as wsdkCommands_dot_WSDK__EnumOTAError__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_NotifyOTAStatus.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1aWSDK_NotifyOTAStatus.proto\x12\rwsdk_commands\x1a$wsdkCommands/WSDK_EnumOTAState.proto\x1a$wsdkCommands/WSDK_EnumOTAError.proto\"\x98\x01\n\x14WSDK_NotifyOTAStatus\x12\x33\n\tota_state\x18\x01 \x01(\x0e\x32 .wsdk_commands.WSDK_EnumOTAState\x12\x16\n\x0eota_percentage\x18\x02 \x01(\x05\x12\x33\n\tota_error\x18\x03 \x01(\x0e\x32 .wsdk_commands.WSDK_EnumOTAError'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumOTAState__pb2.DESCRIPTOR,wsdkCommands_dot_WSDK__EnumOTAError__pb2.DESCRIPTOR,])




_WSDK_NOTIFYOTASTATUS = _descriptor.Descriptor(
  name='WSDK_NotifyOTAStatus',
  full_name='wsdk_commands.WSDK_NotifyOTAStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ota_state', full_name='wsdk_commands.WSDK_NotifyOTAStatus.ota_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ota_percentage', full_name='wsdk_commands.WSDK_NotifyOTAStatus.ota_percentage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ota_error', full_name='wsdk_commands.WSDK_NotifyOTAStatus.ota_error', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=274,
)

_WSDK_NOTIFYOTASTATUS.fields_by_name['ota_state'].enum_type = wsdkCommands_dot_WSDK__EnumOTAState__pb2._WSDK_ENUMOTASTATE
_WSDK_NOTIFYOTASTATUS.fields_by_name['ota_error'].enum_type = wsdkCommands_dot_WSDK__EnumOTAError__pb2._WSDK_ENUMOTAERROR
DESCRIPTOR.message_types_by_name['WSDK_NotifyOTAStatus'] = _WSDK_NOTIFYOTASTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_NotifyOTAStatus = _reflection.GeneratedProtocolMessageType('WSDK_NotifyOTAStatus', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_NOTIFYOTASTATUS,
  '__module__' : 'WSDK_NotifyOTAStatus_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_NotifyOTAStatus)
  })
_sym_db.RegisterMessage(WSDK_NotifyOTAStatus)


# @@protoc_insertion_point(module_scope)
