# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WSDK_RequestGetPresetStatus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumRegisterPresetStatus_pb2 as wsdkCommands_dot_WSDK__EnumRegisterPresetStatus__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WSDK_RequestGetPresetStatus.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n!WSDK_RequestGetPresetStatus.proto\x12\rwsdk_commands\x1a\x30wsdkCommands/WSDK_EnumRegisterPresetStatus.proto\"\xbb\x01\n\x1bWSDK_RequestGetPresetStatus\x12L\n\x16register_preset_status\x18\x01 \x03(\x0e\x32,.wsdk_commands.WSDK_EnumRegisterPresetStatus\x12N\n\x18unregister_preset_status\x18\x02 \x03(\x0e\x32,.wsdk_commands.WSDK_EnumRegisterPresetStatus'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumRegisterPresetStatus__pb2.DESCRIPTOR,])




_WSDK_REQUESTGETPRESETSTATUS = _descriptor.Descriptor(
  name='WSDK_RequestGetPresetStatus',
  full_name='wsdk_commands.WSDK_RequestGetPresetStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='register_preset_status', full_name='wsdk_commands.WSDK_RequestGetPresetStatus.register_preset_status', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unregister_preset_status', full_name='wsdk_commands.WSDK_RequestGetPresetStatus.unregister_preset_status', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=290,
)

_WSDK_REQUESTGETPRESETSTATUS.fields_by_name['register_preset_status'].enum_type = wsdkCommands_dot_WSDK__EnumRegisterPresetStatus__pb2._WSDK_ENUMREGISTERPRESETSTATUS
_WSDK_REQUESTGETPRESETSTATUS.fields_by_name['unregister_preset_status'].enum_type = wsdkCommands_dot_WSDK__EnumRegisterPresetStatus__pb2._WSDK_ENUMREGISTERPRESETSTATUS
DESCRIPTOR.message_types_by_name['WSDK_RequestGetPresetStatus'] = _WSDK_REQUESTGETPRESETSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_RequestGetPresetStatus = _reflection.GeneratedProtocolMessageType('WSDK_RequestGetPresetStatus', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_REQUESTGETPRESETSTATUS,
  '__module__' : 'WSDK_RequestGetPresetStatus_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_RequestGetPresetStatus)
  })
_sym_db.RegisterMessage(WSDK_RequestGetPresetStatus)


# @@protoc_insertion_point(module_scope)
