# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumAuthState.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumAuthState.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n%wsdkCommands/WSDK_EnumAuthState.proto\x12\rwsdk_commands*\xf4\x01\n\x12WSDK_EnumAuthState\x12\x1b\n\x17WSDK_AUTH_STATE_UNKNOWN\x10\x00\x12\x1e\n\x1aWSDK_AUTH_STATE_AUTHORIZED\x10\x01\x12\"\n\x1eWSDK_AUTH_STATE_NOT_AUTHORIZED\x10\x02\x12\x18\n\x14WSDK_AUTH_STATE_BUSY\x10\x03\x12\x1f\n\x1bWSDK_AUTH_STATE_ERR_NETWORK\x10\x04\x12\x1d\n\x19WSDK_AUTH_STATE_ERR_CLOUD\x10\x05\x12#\n\x1fWSDK_AUTH_STATE_ERR_AUTH_FAILED\x10\x06'
)

_WSDK_ENUMAUTHSTATE = _descriptor.EnumDescriptor(
  name='WSDK_EnumAuthState',
  full_name='wsdk_commands.WSDK_EnumAuthState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_AUTH_STATE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_AUTH_STATE_AUTHORIZED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_AUTH_STATE_NOT_AUTHORIZED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_AUTH_STATE_BUSY', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_AUTH_STATE_ERR_NETWORK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_AUTH_STATE_ERR_CLOUD', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_AUTH_STATE_ERR_AUTH_FAILED', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=57,
  serialized_end=301,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMAUTHSTATE)

WSDK_EnumAuthState = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMAUTHSTATE)
WSDK_AUTH_STATE_UNKNOWN = 0
WSDK_AUTH_STATE_AUTHORIZED = 1
WSDK_AUTH_STATE_NOT_AUTHORIZED = 2
WSDK_AUTH_STATE_BUSY = 3
WSDK_AUTH_STATE_ERR_NETWORK = 4
WSDK_AUTH_STATE_ERR_CLOUD = 5
WSDK_AUTH_STATE_ERR_AUTH_FAILED = 6


DESCRIPTOR.enum_types_by_name['WSDK_EnumAuthState'] = _WSDK_ENUMAUTHSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
