# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_PresetSetting.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_PresetSetting.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n%wsdkCommands/WSDK_PresetSetting.proto\x12\rwsdk_commands\"C\n\x12WSDK_PresetSetting\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x12\n\nis_caption\x18\x03 \x01(\x08'
)




_WSDK_PRESETSETTING = _descriptor.Descriptor(
  name='WSDK_PresetSetting',
  full_name='wsdk_commands.WSDK_PresetSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='wsdk_commands.WSDK_PresetSetting.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='wsdk_commands.WSDK_PresetSetting.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_caption', full_name='wsdk_commands.WSDK_PresetSetting.is_caption', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['WSDK_PresetSetting'] = _WSDK_PRESETSETTING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_PresetSetting = _reflection.GeneratedProtocolMessageType('WSDK_PresetSetting', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_PRESETSETTING,
  '__module__' : 'wsdkCommands.WSDK_PresetSetting_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_PresetSetting)
  })
_sym_db.RegisterMessage(WSDK_PresetSetting)


# @@protoc_insertion_point(module_scope)
