# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumOTAError.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumOTAError.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n$wsdkCommands/WSDK_EnumOTAError.proto\x12\rwsdk_commands*\xb4\x03\n\x11WSDK_EnumOTAError\x12\x17\n\x13WSDK_OTA_ERROR_NONE\x10\x00\x12\x1a\n\x16WSDK_OTA_ERROR_CSIFAIL\x10\x01\x12\x1c\n\x18WSDK_OTA_ERROR_UNZIPFAIL\x10\x02\x12\"\n\x1eWSDK_OTA_ERROR_HEADREQUESTFAIL\x10\x03\x12\x1f\n\x1bWSDK_OTA_ERROR_DOWNLOADFAIL\x10\x04\x12\x1e\n\x1aWSDK_OTA_ERROR_NETWORKFAIL\x10\x05\x12 \n\x1cWSDK_OTA_ERROR_GOPROPINGFAIL\x10\x06\x12\x1f\n\x1bWSDK_OTA_ERROR_CURLINITFAIL\x10\x07\x12\x1e\n\x1aWSDK_OTA_ERROR_SHA_FAILURE\x10\x08\x12\x1b\n\x17WSDK_OTA_ERROR_FILESIZE\x10\t\x12\x1c\n\x18WSDK_OTA_ERROR_THREADING\x10\n\x12\"\n\x1eWSDK_OTA_ERROR_NOFIRMWAREFOUND\x10\x0b\x12%\n!WSDK_OTA_ERROR_FIRMWAREDIDNTMATCH\x10\x0c'
)

_WSDK_ENUMOTAERROR = _descriptor.EnumDescriptor(
  name='WSDK_EnumOTAError',
  full_name='wsdk_commands.WSDK_EnumOTAError',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_CSIFAIL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_UNZIPFAIL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_HEADREQUESTFAIL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_DOWNLOADFAIL', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_NETWORKFAIL', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_GOPROPINGFAIL', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_CURLINITFAIL', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_SHA_FAILURE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_FILESIZE', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_THREADING', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_NOFIRMWAREFOUND', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_ERROR_FIRMWAREDIDNTMATCH', index=12, number=12,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=56,
  serialized_end=492,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMOTAERROR)

WSDK_EnumOTAError = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMOTAERROR)
WSDK_OTA_ERROR_NONE = 0
WSDK_OTA_ERROR_CSIFAIL = 1
WSDK_OTA_ERROR_UNZIPFAIL = 2
WSDK_OTA_ERROR_HEADREQUESTFAIL = 3
WSDK_OTA_ERROR_DOWNLOADFAIL = 4
WSDK_OTA_ERROR_NETWORKFAIL = 5
WSDK_OTA_ERROR_GOPROPINGFAIL = 6
WSDK_OTA_ERROR_CURLINITFAIL = 7
WSDK_OTA_ERROR_SHA_FAILURE = 8
WSDK_OTA_ERROR_FILESIZE = 9
WSDK_OTA_ERROR_THREADING = 10
WSDK_OTA_ERROR_NOFIRMWAREFOUND = 11
WSDK_OTA_ERROR_FIRMWAREDIDNTMATCH = 12


DESCRIPTOR.enum_types_by_name['WSDK_EnumOTAError'] = _WSDK_ENUMOTAERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
