# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumBandSelect.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumBandSelect.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n&wsdkCommands/WSDK_EnumBandSelect.proto\x12\rwsdk_commands*]\n\x13WSDK_EnumBandSelect\x12\x1b\n\x17WSDK_BAND_SELECT_2_4GHZ\x10\x00\x12\x14\n\x10\x42\x41ND_SELECT_5GHZ\x10\x01\x12\x13\n\x0f\x42\x41ND_SELECT_MAX\x10\x02'
)

_WSDK_ENUMBANDSELECT = _descriptor.EnumDescriptor(
  name='WSDK_EnumBandSelect',
  full_name='wsdk_commands.WSDK_EnumBandSelect',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_BAND_SELECT_2_4GHZ', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAND_SELECT_5GHZ', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAND_SELECT_MAX', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=57,
  serialized_end=150,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMBANDSELECT)

WSDK_EnumBandSelect = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMBANDSELECT)
WSDK_BAND_SELECT_2_4GHZ = 0
BAND_SELECT_5GHZ = 1
BAND_SELECT_MAX = 2


DESCRIPTOR.enum_types_by_name['WSDK_EnumBandSelect'] = _WSDK_ENUMBANDSELECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
