# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumPresetTitle.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumPresetTitle.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\'wsdkCommands/WSDK_EnumPresetTitle.proto\x12\rwsdk_commands*\xa2\x08\n\x14WSDK_EnumPresetTitle\x12\x1e\n\x1aWSDK_PRESET_TITLE_ACTIVITY\x10\x00\x12\x1e\n\x1aWSDK_PRESET_TITLE_STANDARD\x10\x01\x12\x1f\n\x1bWSDK_PRESET_TITLE_CINEMATIC\x10\x02\x12\x1b\n\x17WSDK_PRESET_TITLE_PHOTO\x10\x03\x12 \n\x1cWSDK_PRESET_TITLE_LIVE_BURST\x10\x04\x12\x1b\n\x17WSDK_PRESET_TITLE_BURST\x10\x05\x12\x1b\n\x17WSDK_PRESET_TITLE_NIGHT\x10\x06\x12\x1f\n\x1bWSDK_PRESET_TITLE_TIME_WARP\x10\x07\x12 \n\x1cWSDK_PRESET_TITLE_TIME_LAPSE\x10\x08\x12!\n\x1dWSDK_PRESET_TITLE_NIGHT_LAPSE\x10\t\x12\x1b\n\x17WSDK_PRESET_TITLE_VIDEO\x10\n\x12\x1b\n\x17WSDK_PRESET_TITLE_SLOMO\x10\x0b\x12\x1f\n\x1bWSDK_PRESET_TITLE_360_VIDEO\x10\x0c\x12\x1d\n\x19WSDK_PRESET_TITLE_PHOTO_2\x10\r\x12\x1e\n\x1aWSDK_PRESET_TITLE_PANORAMA\x10\x0e\x12\x1f\n\x1bWSDK_PRESET_TITLE_360_PHOTO\x10\x0f\x12!\n\x1dWSDK_PRESET_TITLE_TIME_WARP_2\x10\x10\x12\x1c\n\x18WSDK_PRESET_TITLE_CUSTOM\x10\x12\x12\x19\n\x15WSDK_PRESET_TITLE_AIR\x10\x13\x12\x1a\n\x16WSDK_PRESET_TITLE_BIKE\x10\x14\x12\x1a\n\x16WSDK_PRESET_TITLE_EPIC\x10\x15\x12\x1c\n\x18WSDK_PRESET_TITLE_INDOOR\x10\x16\x12\x1b\n\x17WSDK_PRESET_TITLE_MOTOR\x10\x17\x12\x1d\n\x19WSDK_PRESET_TITLE_MOUNTED\x10\x18\x12\x1d\n\x19WSDK_PRESET_TITLE_OUTDOOR\x10\x19\x12\x19\n\x15WSDK_PRESET_TITLE_POV\x10\x1a\x12\x1c\n\x18WSDK_PRESET_TITLE_SELFIE\x10\x1b\x12\x1b\n\x17WSDK_PRESET_TITLE_SKATE\x10\x1c\x12\x1a\n\x16WSDK_PRESET_TITLE_SNOW\x10\x1d\x12\x1b\n\x17WSDK_PRESET_TITLE_TRAIL\x10\x1e\x12\x1c\n\x18WSDK_PRESET_TITLE_TRAVEL\x10\x1f\x12\x1b\n\x17WSDK_PRESET_TITLE_WATER\x10 \x12\x1d\n\x19WSDK_PRESET_TITLE_LOOPING\x10!\x12\x19\n\x15WSDK_PRESET_TITLE_MAX\x10\"'
)

_WSDK_ENUMPRESETTITLE = _descriptor.EnumDescriptor(
  name='WSDK_EnumPresetTitle',
  full_name='wsdk_commands.WSDK_EnumPresetTitle',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_ACTIVITY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_STANDARD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_CINEMATIC', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_PHOTO', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_LIVE_BURST', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_BURST', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_NIGHT', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_TIME_WARP', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_TIME_LAPSE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_NIGHT_LAPSE', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_VIDEO', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_SLOMO', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_360_VIDEO', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_PHOTO_2', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_PANORAMA', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_360_PHOTO', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_TIME_WARP_2', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_CUSTOM', index=17, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_AIR', index=18, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_BIKE', index=19, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_EPIC', index=20, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_INDOOR', index=21, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_MOTOR', index=22, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_MOUNTED', index=23, number=24,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_OUTDOOR', index=24, number=25,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_POV', index=25, number=26,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_SELFIE', index=26, number=27,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_SKATE', index=27, number=28,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_SNOW', index=28, number=29,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_TRAIL', index=29, number=30,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_TRAVEL', index=30, number=31,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_WATER', index=31, number=32,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_LOOPING', index=32, number=33,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_PRESET_TITLE_MAX', index=33, number=34,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=59,
  serialized_end=1117,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMPRESETTITLE)

WSDK_EnumPresetTitle = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMPRESETTITLE)
WSDK_PRESET_TITLE_ACTIVITY = 0
WSDK_PRESET_TITLE_STANDARD = 1
WSDK_PRESET_TITLE_CINEMATIC = 2
WSDK_PRESET_TITLE_PHOTO = 3
WSDK_PRESET_TITLE_LIVE_BURST = 4
WSDK_PRESET_TITLE_BURST = 5
WSDK_PRESET_TITLE_NIGHT = 6
WSDK_PRESET_TITLE_TIME_WARP = 7
WSDK_PRESET_TITLE_TIME_LAPSE = 8
WSDK_PRESET_TITLE_NIGHT_LAPSE = 9
WSDK_PRESET_TITLE_VIDEO = 10
WSDK_PRESET_TITLE_SLOMO = 11
WSDK_PRESET_TITLE_360_VIDEO = 12
WSDK_PRESET_TITLE_PHOTO_2 = 13
WSDK_PRESET_TITLE_PANORAMA = 14
WSDK_PRESET_TITLE_360_PHOTO = 15
WSDK_PRESET_TITLE_TIME_WARP_2 = 16
WSDK_PRESET_TITLE_CUSTOM = 18
WSDK_PRESET_TITLE_AIR = 19
WSDK_PRESET_TITLE_BIKE = 20
WSDK_PRESET_TITLE_EPIC = 21
WSDK_PRESET_TITLE_INDOOR = 22
WSDK_PRESET_TITLE_MOTOR = 23
WSDK_PRESET_TITLE_MOUNTED = 24
WSDK_PRESET_TITLE_OUTDOOR = 25
WSDK_PRESET_TITLE_POV = 26
WSDK_PRESET_TITLE_SELFIE = 27
WSDK_PRESET_TITLE_SKATE = 28
WSDK_PRESET_TITLE_SNOW = 29
WSDK_PRESET_TITLE_TRAIL = 30
WSDK_PRESET_TITLE_TRAVEL = 31
WSDK_PRESET_TITLE_WATER = 32
WSDK_PRESET_TITLE_LOOPING = 33
WSDK_PRESET_TITLE_MAX = 34


DESCRIPTOR.enum_types_by_name['WSDK_EnumPresetTitle'] = _WSDK_ENUMPRESETTITLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
