# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumOTAState.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumOTAState.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n$wsdkCommands/WSDK_EnumOTAState.proto\x12\rwsdk_commands*\x8b\x03\n\x11WSDK_EnumOTAState\x12\x17\n\x13WSDK_OTA_STATE_IDLE\x10\x00\x12\x1e\n\x1aWSDK_OTA_STATE_DOWNLOADING\x10\x01\x12\x1c\n\x18WSDK_OTA_STATE_VERIFYING\x10\x02\x12\"\n\x1eWSDK_OTA_STATE_DOWNLOAD_FAILED\x10\x03\x12 \n\x1cWSDK_OTA_STATE_VERIFY_FAILED\x10\x04\x12\x18\n\x14WSDK_OTA_STATE_READY\x10\x05\x12%\n!WSDK_OTA_STATE_SMARTY_DOWNLOADING\x10\x06\x12#\n\x1fWSDK_OTA_STATE_SMARTY_VERIFYING\x10\x07\x12)\n%WSDK_OTA_STATE_SMARTY_DOWNLOAD_FAILED\x10\x08\x12\'\n#WSDK_OTA_STATE_SMARTY_VERIFY_FAILED\x10\t\x12\x1f\n\x1bWSDK_OTA_STATE_SMARTY_READY\x10\n'
)

_WSDK_ENUMOTASTATE = _descriptor.EnumDescriptor(
  name='WSDK_EnumOTAState',
  full_name='wsdk_commands.WSDK_EnumOTAState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_STATE_IDLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_STATE_DOWNLOADING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_STATE_VERIFYING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_STATE_DOWNLOAD_FAILED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_STATE_VERIFY_FAILED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_STATE_READY', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_STATE_SMARTY_DOWNLOADING', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_STATE_SMARTY_VERIFYING', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_STATE_SMARTY_DOWNLOAD_FAILED', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_STATE_SMARTY_VERIFY_FAILED', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_STATE_SMARTY_READY', index=10, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=56,
  serialized_end=451,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMOTASTATE)

WSDK_EnumOTAState = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMOTASTATE)
WSDK_OTA_STATE_IDLE = 0
WSDK_OTA_STATE_DOWNLOADING = 1
WSDK_OTA_STATE_VERIFYING = 2
WSDK_OTA_STATE_DOWNLOAD_FAILED = 3
WSDK_OTA_STATE_VERIFY_FAILED = 4
WSDK_OTA_STATE_READY = 5
WSDK_OTA_STATE_SMARTY_DOWNLOADING = 6
WSDK_OTA_STATE_SMARTY_VERIFYING = 7
WSDK_OTA_STATE_SMARTY_DOWNLOAD_FAILED = 8
WSDK_OTA_STATE_SMARTY_VERIFY_FAILED = 9
WSDK_OTA_STATE_SMARTY_READY = 10


DESCRIPTOR.enum_types_by_name['WSDK_EnumOTAState'] = _WSDK_ENUMOTASTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
