# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumWOM.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumWOM.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1fwsdkCommands/WSDK_EnumWOM.proto\x12\rwsdk_commands*\xd4\x04\n\x11WSDK_EnumWOMState\x12\x17\n\x13WSDK_WOM_STATE_INIT\x10\x00\x12\x18\n\x14WSDK_WOM_STATE_ERROR\x10\x01\x12\x17\n\x13WSDK_WOM_STATE_EXIT\x10\x02\x12 \n\x1cWSDK_WOM_STATE_CSI_SUBSCRIBE\x10\x03\x12\"\n\x1eWSDK_WOM_STATE_CSI_UNSUBSCRIBE\x10\x04\x12 \n\x1cWSDK_WOM_STATE_NOT_TRIGGERED\x10\x05\x12\x17\n\x13WSDK_WOM_STATE_EVAL\x10\x06\x12\x1a\n\x16WSDK_WOM_STATE_ENTERED\x10\x07\x12\x1e\n\x1aWSDK_WOM_STATE_NOT_ENTERED\x10\x08\x12$\n WSDK_WOM_STATE_CANCEL_OK_STAY_ON\x10\t\x12%\n!WSDK_WOM_STATE_CONNECTING_TO_SINK\x10\n\x12!\n\x1dWSDK_WOM_STATE_FAILED_STAY_ON\x10\x0b\x12!\n\x1dWSDK_WOM_STATE_OFFLOADING_CAH\x10\x0c\x12 \n\x1cWSDK_WOM_STATE_OFFLOADING_ST\x10\r\x12#\n\x1fWSDK_WOM_STATE_COMPLETE_STAY_ON\x10\x0e\x12$\n WSDK_WOM_STATE_COMPLETE_TURN_OFF\x10\x0f\x12\x1a\n\x16WSDK_WOM_STATE_INVALID\x10\x10\x12\x1a\n\x16WSDK_WOM_STATE_CSI_ERR\x10\x7f*+\n\x0fWSDK_EnumWOMCat\x12\x18\n\x14WSDK_WOM_CAT_CSI_ERR\x10\x7f*+\n\x0fWSDK_EnumWOMSub\x12\x18\n\x14WSDK_WOM_SUB_CSI_ERR\x10\x7f*\xac\x04\n\x0fWSDK_EnumWOMErr\x12\x17\n\x13WSDK_WOM_ERR_NO_ERR\x10\x00\x12\x18\n\x14WSDK_WOM_ERR_MQ_OPEN\x10\x01\x12\x1b\n\x17WSDK_WOM_ERR_ALLOCATION\x10\x02\x12\x1b\n\x17WSDK_WOM_ERR_MQ_RECEIVE\x10\x03\x12\x1e\n\x1aWSDK_WOM_ERR_MESSAGE_PARSE\x10\x04\x12\x14\n\x10WSDK_WOM_ERR_CSI\x10\x05\x12\x1e\n\x1aWSDK_WOM_ERR_INVALID_EVENT\x10\x06\x12\x1d\n\x19WSDK_WOM_ERR_START_FAILED\x10\x07\x12\x19\n\x15WSDK_WOM_ERR_NRA_NACK\x10\x08\x12\x1e\n\x1aWSDK_WOM_ERR_NRA_OWNERSHIP\x10\t\x12\x1c\n\x18WSDK_WOM_ERR_NRA_TIMEOUT\x10\n\x12\x1d\n\x19WSDK_WOM_ERR_LOST_NETWORK\x10\x0b\x12\x18\n\x14WSDK_WOM_ERR_SD_CARD\x10\x0c\x12\x1e\n\x1aWSDK_WOM_ERR_SD_CARD_SPACE\x10\r\x12\x1d\n\x19WSDK_WOM_ERR_NO_NEW_MEDIA\x10\x0e\x12#\n\x1fWSDK_WOM_ERR_SPACE_CHECK_FAILED\x10\x0f\x12\'\n#WSDK_WOM_ERR_NEW_MEDIA_CHECK_FAILED\x10\x10\x12\x18\n\x14WSDK_WOM_ERR_CSI_ERR\x10\x7f'
)

_WSDK_ENUMWOMSTATE = _descriptor.EnumDescriptor(
  name='WSDK_EnumWOMState',
  full_name='wsdk_commands.WSDK_EnumWOMState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_INIT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_EXIT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_CSI_SUBSCRIBE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_CSI_UNSUBSCRIBE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_NOT_TRIGGERED', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_EVAL', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_ENTERED', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_NOT_ENTERED', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_CANCEL_OK_STAY_ON', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_CONNECTING_TO_SINK', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_FAILED_STAY_ON', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_OFFLOADING_CAH', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_OFFLOADING_ST', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_COMPLETE_STAY_ON', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_COMPLETE_TURN_OFF', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_INVALID', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_STATE_CSI_ERR', index=17, number=127,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=51,
  serialized_end=647,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMWOMSTATE)

WSDK_EnumWOMState = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMWOMSTATE)
_WSDK_ENUMWOMCAT = _descriptor.EnumDescriptor(
  name='WSDK_EnumWOMCat',
  full_name='wsdk_commands.WSDK_EnumWOMCat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_CAT_CSI_ERR', index=0, number=127,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=649,
  serialized_end=692,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMWOMCAT)

WSDK_EnumWOMCat = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMWOMCAT)
_WSDK_ENUMWOMSUB = _descriptor.EnumDescriptor(
  name='WSDK_EnumWOMSub',
  full_name='wsdk_commands.WSDK_EnumWOMSub',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_SUB_CSI_ERR', index=0, number=127,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=694,
  serialized_end=737,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMWOMSUB)

WSDK_EnumWOMSub = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMWOMSUB)
_WSDK_ENUMWOMERR = _descriptor.EnumDescriptor(
  name='WSDK_EnumWOMErr',
  full_name='wsdk_commands.WSDK_EnumWOMErr',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_NO_ERR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_MQ_OPEN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_ALLOCATION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_MQ_RECEIVE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_MESSAGE_PARSE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_CSI', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_INVALID_EVENT', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_START_FAILED', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_NRA_NACK', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_NRA_OWNERSHIP', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_NRA_TIMEOUT', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_LOST_NETWORK', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_SD_CARD', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_SD_CARD_SPACE', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_NO_NEW_MEDIA', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_SPACE_CHECK_FAILED', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_NEW_MEDIA_CHECK_FAILED', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_WOM_ERR_CSI_ERR', index=17, number=127,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=740,
  serialized_end=1296,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMWOMERR)

WSDK_EnumWOMErr = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMWOMERR)
WSDK_WOM_STATE_INIT = 0
WSDK_WOM_STATE_ERROR = 1
WSDK_WOM_STATE_EXIT = 2
WSDK_WOM_STATE_CSI_SUBSCRIBE = 3
WSDK_WOM_STATE_CSI_UNSUBSCRIBE = 4
WSDK_WOM_STATE_NOT_TRIGGERED = 5
WSDK_WOM_STATE_EVAL = 6
WSDK_WOM_STATE_ENTERED = 7
WSDK_WOM_STATE_NOT_ENTERED = 8
WSDK_WOM_STATE_CANCEL_OK_STAY_ON = 9
WSDK_WOM_STATE_CONNECTING_TO_SINK = 10
WSDK_WOM_STATE_FAILED_STAY_ON = 11
WSDK_WOM_STATE_OFFLOADING_CAH = 12
WSDK_WOM_STATE_OFFLOADING_ST = 13
WSDK_WOM_STATE_COMPLETE_STAY_ON = 14
WSDK_WOM_STATE_COMPLETE_TURN_OFF = 15
WSDK_WOM_STATE_INVALID = 16
WSDK_WOM_STATE_CSI_ERR = 127
WSDK_WOM_CAT_CSI_ERR = 127
WSDK_WOM_SUB_CSI_ERR = 127
WSDK_WOM_ERR_NO_ERR = 0
WSDK_WOM_ERR_MQ_OPEN = 1
WSDK_WOM_ERR_ALLOCATION = 2
WSDK_WOM_ERR_MQ_RECEIVE = 3
WSDK_WOM_ERR_MESSAGE_PARSE = 4
WSDK_WOM_ERR_CSI = 5
WSDK_WOM_ERR_INVALID_EVENT = 6
WSDK_WOM_ERR_START_FAILED = 7
WSDK_WOM_ERR_NRA_NACK = 8
WSDK_WOM_ERR_NRA_OWNERSHIP = 9
WSDK_WOM_ERR_NRA_TIMEOUT = 10
WSDK_WOM_ERR_LOST_NETWORK = 11
WSDK_WOM_ERR_SD_CARD = 12
WSDK_WOM_ERR_SD_CARD_SPACE = 13
WSDK_WOM_ERR_NO_NEW_MEDIA = 14
WSDK_WOM_ERR_SPACE_CHECK_FAILED = 15
WSDK_WOM_ERR_NEW_MEDIA_CHECK_FAILED = 16
WSDK_WOM_ERR_CSI_ERR = 127


DESCRIPTOR.enum_types_by_name['WSDK_EnumWOMState'] = _WSDK_ENUMWOMSTATE
DESCRIPTOR.enum_types_by_name['WSDK_EnumWOMCat'] = _WSDK_ENUMWOMCAT
DESCRIPTOR.enum_types_by_name['WSDK_EnumWOMSub'] = _WSDK_ENUMWOMSUB
DESCRIPTOR.enum_types_by_name['WSDK_EnumWOMErr'] = _WSDK_ENUMWOMERR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
