# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumAssociationState.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumAssociationState.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n,wsdkCommands/WSDK_EnumAssociationState.proto\x12\rwsdk_commands*\xa1\x01\n\x19WSDK_EnumAssociationState\x12)\n%WSDK_ASSOCIATION_STATE_NOT_ASSOCIATED\x10\x00\x12%\n!WSDK_ASSOCIATION_STATE_ASSOCIATED\x10\x01\x12\x32\n.WSDK_ASSOCIATION_STATE_ASSOCIATED_ANOTHER_USER\x10\x02'
)

_WSDK_ENUMASSOCIATIONSTATE = _descriptor.EnumDescriptor(
  name='WSDK_EnumAssociationState',
  full_name='wsdk_commands.WSDK_EnumAssociationState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_ASSOCIATION_STATE_NOT_ASSOCIATED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_ASSOCIATION_STATE_ASSOCIATED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_ASSOCIATION_STATE_ASSOCIATED_ANOTHER_USER', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=64,
  serialized_end=225,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMASSOCIATIONSTATE)

WSDK_EnumAssociationState = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMASSOCIATIONSTATE)
WSDK_ASSOCIATION_STATE_NOT_ASSOCIATED = 0
WSDK_ASSOCIATION_STATE_ASSOCIATED = 1
WSDK_ASSOCIATION_STATE_ASSOCIATED_ANOTHER_USER = 2


DESCRIPTOR.enum_types_by_name['WSDK_EnumAssociationState'] = _WSDK_ENUMASSOCIATIONSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
