# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumSystemNotifyEvent.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumSystemNotifyEvent.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n-wsdkCommands/WSDK_EnumSystemNotifyEvent.proto\x12\rwsdk_commands*\xad\x01\n\x1aWSDK_EnumSystemNotifyEvent\x12\x19\n\x15WSDK_ACTIVITY_UNKNOWN\x10\x00\x12\x1a\n\x16WSDK_ACTIVITY_ST_START\x10\x01\x12\x1d\n\x19WSDK_ACTIVITY_ST_POWER_ON\x10\x02\x12\x19\n\x15WSDK_ACTIVITY_ST_STOP\x10\x03\x12\x1e\n\x1aWSDK_ACTIVITY_APP_POWER_UP\x10\x04'
)

_WSDK_ENUMSYSTEMNOTIFYEVENT = _descriptor.EnumDescriptor(
  name='WSDK_EnumSystemNotifyEvent',
  full_name='wsdk_commands.WSDK_EnumSystemNotifyEvent',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_ACTIVITY_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_ACTIVITY_ST_START', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_ACTIVITY_ST_POWER_ON', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_ACTIVITY_ST_STOP', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_ACTIVITY_APP_POWER_UP', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=65,
  serialized_end=238,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMSYSTEMNOTIFYEVENT)

WSDK_EnumSystemNotifyEvent = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMSYSTEMNOTIFYEVENT)
WSDK_ACTIVITY_UNKNOWN = 0
WSDK_ACTIVITY_ST_START = 1
WSDK_ACTIVITY_ST_POWER_ON = 2
WSDK_ACTIVITY_ST_STOP = 3
WSDK_ACTIVITY_APP_POWER_UP = 4


DESCRIPTOR.enum_types_by_name['WSDK_EnumSystemNotifyEvent'] = _WSDK_ENUMSYSTEMNOTIFYEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
