# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumRegisterPresetStatus.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumRegisterPresetStatus.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n0wsdkCommands/WSDK_EnumRegisterPresetStatus.proto\x12\rwsdk_commands*{\n\x1dWSDK_EnumRegisterPresetStatus\x12&\n\"WSDK_REGISTER_PRESET_STATUS_PRESET\x10\x01\x12\x32\n.WSDK_REGISTER_PRESET_STATUS_PRESET_GROUP_ARRAY\x10\x02'
)

_WSDK_ENUMREGISTERPRESETSTATUS = _descriptor.EnumDescriptor(
  name='WSDK_EnumRegisterPresetStatus',
  full_name='wsdk_commands.WSDK_EnumRegisterPresetStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_PRESET_STATUS_PRESET', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_PRESET_STATUS_PRESET_GROUP_ARRAY', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=67,
  serialized_end=190,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMREGISTERPRESETSTATUS)

WSDK_EnumRegisterPresetStatus = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMREGISTERPRESETSTATUS)
WSDK_REGISTER_PRESET_STATUS_PRESET = 1
WSDK_REGISTER_PRESET_STATUS_PRESET_GROUP_ARRAY = 2


DESCRIPTOR.enum_types_by_name['WSDK_EnumRegisterPresetStatus'] = _WSDK_ENUMREGISTERPRESETSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
