# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_PresetGroup.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumPresetGroup_pb2 as wsdkCommands_dot_WSDK__EnumPresetGroup__pb2
from wsdkCommands import WSDK_Preset_pb2 as wsdkCommands_dot_WSDK__Preset__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_PresetGroup.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n#wsdkCommands/WSDK_PresetGroup.proto\x12\rwsdk_commands\x1a\'wsdkCommands/WSDK_EnumPresetGroup.proto\x1a\x1ewsdkCommands/WSDK_Preset.proto\"\x8d\x01\n\x10WSDK_PresetGroup\x12/\n\x02id\x18\x01 \x01(\x0e\x32#.wsdk_commands.WSDK_EnumPresetGroup\x12\x30\n\x0cpreset_array\x18\x02 \x03(\x0b\x32\x1a.wsdk_commands.WSDK_Preset\x12\x16\n\x0e\x63\x61n_add_preset\x18\x03 \x01(\x08'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumPresetGroup__pb2.DESCRIPTOR,wsdkCommands_dot_WSDK__Preset__pb2.DESCRIPTOR,])




_WSDK_PRESETGROUP = _descriptor.Descriptor(
  name='WSDK_PresetGroup',
  full_name='wsdk_commands.WSDK_PresetGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='wsdk_commands.WSDK_PresetGroup.id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preset_array', full_name='wsdk_commands.WSDK_PresetGroup.preset_array', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='can_add_preset', full_name='wsdk_commands.WSDK_PresetGroup.can_add_preset', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=269,
)

_WSDK_PRESETGROUP.fields_by_name['id'].enum_type = wsdkCommands_dot_WSDK__EnumPresetGroup__pb2._WSDK_ENUMPRESETGROUP
_WSDK_PRESETGROUP.fields_by_name['preset_array'].message_type = wsdkCommands_dot_WSDK__Preset__pb2._WSDK_PRESET
DESCRIPTOR.message_types_by_name['WSDK_PresetGroup'] = _WSDK_PRESETGROUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_PresetGroup = _reflection.GeneratedProtocolMessageType('WSDK_PresetGroup', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_PRESETGROUP,
  '__module__' : 'wsdkCommands.WSDK_PresetGroup_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_PresetGroup)
  })
_sym_db.RegisterMessage(WSDK_PresetGroup)


# @@protoc_insertion_point(module_scope)
