# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumOTACmd.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumOTACmd.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\"wsdkCommands/WSDK_EnumOTACmd.proto\x12\rwsdk_commands*U\n\x0fWSDK_EnumOTACmd\x12\x12\n\x0eWSDK_OTA_START\x10\x05\x12\x19\n\x15WSDK_OTA_START_FORCED\x10\x06\x12\x13\n\x0fWSDK_OTA_CANCEL\x10\x02'
)

_WSDK_ENUMOTACMD = _descriptor.EnumDescriptor(
  name='WSDK_EnumOTACmd',
  full_name='wsdk_commands.WSDK_EnumOTACmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_START', index=0, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_START_FORCED', index=1, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_OTA_CANCEL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=53,
  serialized_end=138,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMOTACMD)

WSDK_EnumOTACmd = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMOTACMD)
WSDK_OTA_START = 5
WSDK_OTA_START_FORCED = 6
WSDK_OTA_CANCEL = 2


DESCRIPTOR.enum_types_by_name['WSDK_EnumOTACmd'] = _WSDK_ENUMOTACMD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
