# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_Preset.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from wsdkCommands import WSDK_EnumPresetIcon_pb2 as wsdkCommands_dot_WSDK__EnumPresetIcon__pb2
from wsdkCommands import WSDK_EnumFlatMode_pb2 as wsdkCommands_dot_WSDK__EnumFlatMode__pb2
from wsdkCommands import WSDK_EnumPresetTitle_pb2 as wsdkCommands_dot_WSDK__EnumPresetTitle__pb2
from wsdkCommands import WSDK_PresetSetting_pb2 as wsdkCommands_dot_WSDK__PresetSetting__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_Preset.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1ewsdkCommands/WSDK_Preset.proto\x12\rwsdk_commands\x1a&wsdkCommands/WSDK_EnumPresetIcon.proto\x1a$wsdkCommands/WSDK_EnumFlatMode.proto\x1a\'wsdkCommands/WSDK_EnumPresetTitle.proto\x1a%wsdkCommands/WSDK_PresetSetting.proto\"\xad\x02\n\x0bWSDK_Preset\x12\n\n\x02id\x18\x01 \x01(\x05\x12.\n\x04mode\x18\x02 \x01(\x0e\x32 .wsdk_commands.WSDK_EnumFlatMode\x12\x35\n\x08title_id\x18\x03 \x01(\x0e\x32#.wsdk_commands.WSDK_EnumPresetTitle\x12\x14\n\x0ctitle_number\x18\x04 \x01(\x05\x12\x14\n\x0cuser_defined\x18\x05 \x01(\x08\x12\x30\n\x04icon\x18\x06 \x01(\x0e\x32\".wsdk_commands.WSDK_EnumPresetIcon\x12\x38\n\rsetting_array\x18\x07 \x03(\x0b\x32!.wsdk_commands.WSDK_PresetSetting\x12\x13\n\x0bis_modified\x18\x08 \x01(\x08'
  ,
  dependencies=[wsdkCommands_dot_WSDK__EnumPresetIcon__pb2.DESCRIPTOR,wsdkCommands_dot_WSDK__EnumFlatMode__pb2.DESCRIPTOR,wsdkCommands_dot_WSDK__EnumPresetTitle__pb2.DESCRIPTOR,wsdkCommands_dot_WSDK__PresetSetting__pb2.DESCRIPTOR,])




_WSDK_PRESET = _descriptor.Descriptor(
  name='WSDK_Preset',
  full_name='wsdk_commands.WSDK_Preset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='wsdk_commands.WSDK_Preset.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='wsdk_commands.WSDK_Preset.mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title_id', full_name='wsdk_commands.WSDK_Preset.title_id', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title_number', full_name='wsdk_commands.WSDK_Preset.title_number', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_defined', full_name='wsdk_commands.WSDK_Preset.user_defined', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon', full_name='wsdk_commands.WSDK_Preset.icon', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setting_array', full_name='wsdk_commands.WSDK_Preset.setting_array', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_modified', full_name='wsdk_commands.WSDK_Preset.is_modified', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=509,
)

_WSDK_PRESET.fields_by_name['mode'].enum_type = wsdkCommands_dot_WSDK__EnumFlatMode__pb2._WSDK_ENUMFLATMODE
_WSDK_PRESET.fields_by_name['title_id'].enum_type = wsdkCommands_dot_WSDK__EnumPresetTitle__pb2._WSDK_ENUMPRESETTITLE
_WSDK_PRESET.fields_by_name['icon'].enum_type = wsdkCommands_dot_WSDK__EnumPresetIcon__pb2._WSDK_ENUMPRESETICON
_WSDK_PRESET.fields_by_name['setting_array'].message_type = wsdkCommands_dot_WSDK__PresetSetting__pb2._WSDK_PRESETSETTING
DESCRIPTOR.message_types_by_name['WSDK_Preset'] = _WSDK_PRESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WSDK_Preset = _reflection.GeneratedProtocolMessageType('WSDK_Preset', (_message.Message,), {
  'DESCRIPTOR' : _WSDK_PRESET,
  '__module__' : 'wsdkCommands.WSDK_Preset_pb2'
  # @@protoc_insertion_point(class_scope:wsdk_commands.WSDK_Preset)
  })
_sym_db.RegisterMessage(WSDK_Preset)


# @@protoc_insertion_point(module_scope)
