# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wsdkCommands/WSDK_EnumRegisterCAHStatus.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wsdkCommands/WSDK_EnumRegisterCAHStatus.proto',
  package='wsdk_commands',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n-wsdkCommands/WSDK_EnumRegisterCAHStatus.proto\x12\rwsdk_commands*\xad\x02\n\x1aWSDK_EnumRegisterCAHStatus\x12$\n WSDK_REGISTER_CAH_STATUS_DEV_MGR\x10\x01\x12 \n\x1cWSDK_REGISTER_CAH_STATUS_WOM\x10\x02\x12!\n\x1dWSDK_REGISTER_CAH_STATUS_CAHA\x10\x03\x12-\n)WSDK_REGISTER_CAH_STATUS_FEATTURE_ENABLED\x10\x04\x12#\n\x1fWSDK_REGISTER_CAH_STATUS_ACTIVE\x10\x05\x12\'\n#WSDK_REGISTER_CAH_STATUS_ASSOCIATED\x10\x06\x12\'\n#WSDK_REGISTER_CAH_STATUS_AUTHORIZED\x10\x07'
)

_WSDK_ENUMREGISTERCAHSTATUS = _descriptor.EnumDescriptor(
  name='WSDK_EnumRegisterCAHStatus',
  full_name='wsdk_commands.WSDK_EnumRegisterCAHStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_CAH_STATUS_DEV_MGR', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_CAH_STATUS_WOM', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_CAH_STATUS_CAHA', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_CAH_STATUS_FEATTURE_ENABLED', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_CAH_STATUS_ACTIVE', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_CAH_STATUS_ASSOCIATED', index=5, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WSDK_REGISTER_CAH_STATUS_AUTHORIZED', index=6, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=65,
  serialized_end=366,
)
_sym_db.RegisterEnumDescriptor(_WSDK_ENUMREGISTERCAHSTATUS)

WSDK_EnumRegisterCAHStatus = enum_type_wrapper.EnumTypeWrapper(_WSDK_ENUMREGISTERCAHSTATUS)
WSDK_REGISTER_CAH_STATUS_DEV_MGR = 1
WSDK_REGISTER_CAH_STATUS_WOM = 2
WSDK_REGISTER_CAH_STATUS_CAHA = 3
WSDK_REGISTER_CAH_STATUS_FEATTURE_ENABLED = 4
WSDK_REGISTER_CAH_STATUS_ACTIVE = 5
WSDK_REGISTER_CAH_STATUS_ASSOCIATED = 6
WSDK_REGISTER_CAH_STATUS_AUTHORIZED = 7


DESCRIPTOR.enum_types_by_name['WSDK_EnumRegisterCAHStatus'] = _WSDK_ENUMREGISTERCAHSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
